// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package jp.metamaps.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePositioningConfiguration (
  val baseUrl: String,
  val mapSlug: String,
  val groupId: String? = null,
  val maxOfflineAgeMs: Long,
  val motionPolicy: String,
  val beaconDiagnosticsEnabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePositioningConfiguration {
      val baseUrl = pigeonVar_list[0] as String
      val mapSlug = pigeonVar_list[1] as String
      val groupId = pigeonVar_list[2] as String?
      val maxOfflineAgeMs = pigeonVar_list[3] as Long
      val motionPolicy = pigeonVar_list[4] as String
      val beaconDiagnosticsEnabled = pigeonVar_list[5] as Boolean
      return NativePositioningConfiguration(baseUrl, mapSlug, groupId, maxOfflineAgeMs, motionPolicy, beaconDiagnosticsEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseUrl,
      mapSlug,
      groupId,
      maxOfflineAgeMs,
      motionPolicy,
      beaconDiagnosticsEnabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePositioningConfiguration
    return MessagesPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && MessagesPigeonUtils.deepEquals(this.mapSlug, other.mapSlug) && MessagesPigeonUtils.deepEquals(this.groupId, other.groupId) && MessagesPigeonUtils.deepEquals(this.maxOfflineAgeMs, other.maxOfflineAgeMs) && MessagesPigeonUtils.deepEquals(this.motionPolicy, other.motionPolicy) && MessagesPigeonUtils.deepEquals(this.beaconDiagnosticsEnabled, other.beaconDiagnosticsEnabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mapSlug)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.groupId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxOfflineAgeMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.motionPolicy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.beaconDiagnosticsEnabled)
    return result
  }
  override fun toString(): String {
    return "NativePositioningConfiguration(baseUrl=$baseUrl, mapSlug=$mapSlug, groupId=$groupId, maxOfflineAgeMs=$maxOfflineAgeMs, motionPolicy=$motionPolicy, beaconDiagnosticsEnabled=$beaconDiagnosticsEnabled)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeOperationResult (
  val error: NativeErrorMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeOperationResult {
      val error = pigeonVar_list[0] as NativeErrorMessage?
      return NativeOperationResult(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeOperationResult
    return MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeOperationResult(error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeClientCreateResult (
  val clientId: Long? = null,
  val error: NativeErrorMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeClientCreateResult {
      val clientId = pigeonVar_list[0] as Long?
      val error = pigeonVar_list[1] as NativeErrorMessage?
      return NativeClientCreateResult(clientId, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeClientCreateResult
    return MessagesPigeonUtils.deepEquals(this.clientId, other.clientId) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeClientCreateResult(clientId=$clientId, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCapabilityResult (
  val report: NativeCapabilityReport? = null,
  val error: NativeErrorMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCapabilityResult {
      val report = pigeonVar_list[0] as NativeCapabilityReport?
      val error = pigeonVar_list[1] as NativeErrorMessage?
      return NativeCapabilityResult(report, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      report,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCapabilityResult
    return MessagesPigeonUtils.deepEquals(this.report, other.report) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.report)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeCapabilityResult(report=$report, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapCenterReticleCandidateResult (
  val candidate: NativeMapCenterReticleCandidate? = null,
  val error: NativeErrorMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapCenterReticleCandidateResult {
      val candidate = pigeonVar_list[0] as NativeMapCenterReticleCandidate?
      val error = pigeonVar_list[1] as NativeErrorMessage?
      return NativeMapCenterReticleCandidateResult(candidate, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      candidate,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMapCenterReticleCandidateResult
    return MessagesPigeonUtils.deepEquals(this.candidate, other.candidate) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.candidate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeMapCenterReticleCandidateResult(candidate=$candidate, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapCenterReticleCandidate (
  val floorId: String,
  val longitude: Double,
  val latitude: Double,
  val local: NativeLocalPosition? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapCenterReticleCandidate {
      val floorId = pigeonVar_list[0] as String
      val longitude = pigeonVar_list[1] as Double
      val latitude = pigeonVar_list[2] as Double
      val local = pigeonVar_list[3] as NativeLocalPosition?
      return NativeMapCenterReticleCandidate(floorId, longitude, latitude, local)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      floorId,
      longitude,
      latitude,
      local,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMapCenterReticleCandidate
    return MessagesPigeonUtils.deepEquals(this.floorId, other.floorId) && MessagesPigeonUtils.deepEquals(this.longitude, other.longitude) && MessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && MessagesPigeonUtils.deepEquals(this.local, other.local)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.local)
    return result
  }
  override fun toString(): String {
    return "NativeMapCenterReticleCandidate(floorId=$floorId, longitude=$longitude, latitude=$latitude, local=$local)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCapabilityReport (
  val platform: String,
  val osVersion: String,
  val sdkVersion: String,
  val ble: NativeBleCapabilities,
  val authorization: NativeAuthorizationCapabilities,
  val sensors: NativeSensorCapabilities,
  val selectedProfile: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCapabilityReport {
      val platform = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val sdkVersion = pigeonVar_list[2] as String
      val ble = pigeonVar_list[3] as NativeBleCapabilities
      val authorization = pigeonVar_list[4] as NativeAuthorizationCapabilities
      val sensors = pigeonVar_list[5] as NativeSensorCapabilities
      val selectedProfile = pigeonVar_list[6] as String
      return NativeCapabilityReport(platform, osVersion, sdkVersion, ble, authorization, sensors, selectedProfile)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      sdkVersion,
      ble,
      authorization,
      sensors,
      selectedProfile,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCapabilityReport
    return MessagesPigeonUtils.deepEquals(this.platform, other.platform) && MessagesPigeonUtils.deepEquals(this.osVersion, other.osVersion) && MessagesPigeonUtils.deepEquals(this.sdkVersion, other.sdkVersion) && MessagesPigeonUtils.deepEquals(this.ble, other.ble) && MessagesPigeonUtils.deepEquals(this.authorization, other.authorization) && MessagesPigeonUtils.deepEquals(this.sensors, other.sensors) && MessagesPigeonUtils.deepEquals(this.selectedProfile, other.selectedProfile)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platform)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sdkVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ble)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authorization)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sensors)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedProfile)
    return result
  }
  override fun toString(): String {
    return "NativeCapabilityReport(platform=$platform, osVersion=$osVersion, sdkVersion=$sdkVersion, ble=$ble, authorization=$authorization, sensors=$sensors, selectedProfile=$selectedProfile)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeBleCapabilities (
  val supported: Boolean,
  val enabled: Boolean,
  val rangingAvailable: Boolean,
  val foregroundScan: Boolean,
  val backgroundScan: String,
  val directionFinding: String,
  val channelSounding: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeBleCapabilities {
      val supported = pigeonVar_list[0] as Boolean
      val enabled = pigeonVar_list[1] as Boolean
      val rangingAvailable = pigeonVar_list[2] as Boolean
      val foregroundScan = pigeonVar_list[3] as Boolean
      val backgroundScan = pigeonVar_list[4] as String
      val directionFinding = pigeonVar_list[5] as String
      val channelSounding = pigeonVar_list[6] as String
      return NativeBleCapabilities(supported, enabled, rangingAvailable, foregroundScan, backgroundScan, directionFinding, channelSounding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supported,
      enabled,
      rangingAvailable,
      foregroundScan,
      backgroundScan,
      directionFinding,
      channelSounding,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeBleCapabilities
    return MessagesPigeonUtils.deepEquals(this.supported, other.supported) && MessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && MessagesPigeonUtils.deepEquals(this.rangingAvailable, other.rangingAvailable) && MessagesPigeonUtils.deepEquals(this.foregroundScan, other.foregroundScan) && MessagesPigeonUtils.deepEquals(this.backgroundScan, other.backgroundScan) && MessagesPigeonUtils.deepEquals(this.directionFinding, other.directionFinding) && MessagesPigeonUtils.deepEquals(this.channelSounding, other.channelSounding)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supported)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rangingAvailable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.foregroundScan)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.backgroundScan)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.directionFinding)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.channelSounding)
    return result
  }
  override fun toString(): String {
    return "NativeBleCapabilities(supported=$supported, enabled=$enabled, rangingAvailable=$rangingAvailable, foregroundScan=$foregroundScan, backgroundScan=$backgroundScan, directionFinding=$directionFinding, channelSounding=$channelSounding)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAuthorizationCapabilities (
  val location: String,
  val preciseLocation: Boolean,
  val bluetoothScan: String,
  val motion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAuthorizationCapabilities {
      val location = pigeonVar_list[0] as String
      val preciseLocation = pigeonVar_list[1] as Boolean
      val bluetoothScan = pigeonVar_list[2] as String
      val motion = pigeonVar_list[3] as String
      return NativeAuthorizationCapabilities(location, preciseLocation, bluetoothScan, motion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      location,
      preciseLocation,
      bluetoothScan,
      motion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAuthorizationCapabilities
    return MessagesPigeonUtils.deepEquals(this.location, other.location) && MessagesPigeonUtils.deepEquals(this.preciseLocation, other.preciseLocation) && MessagesPigeonUtils.deepEquals(this.bluetoothScan, other.bluetoothScan) && MessagesPigeonUtils.deepEquals(this.motion, other.motion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.location)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.preciseLocation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bluetoothScan)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.motion)
    return result
  }
  override fun toString(): String {
    return "NativeAuthorizationCapabilities(location=$location, preciseLocation=$preciseLocation, bluetoothScan=$bluetoothScan, motion=$motion)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeSensorCapabilities (
  val stepDetector: Boolean,
  val rotationVector: Boolean,
  val gyroscope: Boolean,
  val magnetometer: Boolean,
  val barometer: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSensorCapabilities {
      val stepDetector = pigeonVar_list[0] as Boolean
      val rotationVector = pigeonVar_list[1] as Boolean
      val gyroscope = pigeonVar_list[2] as Boolean
      val magnetometer = pigeonVar_list[3] as Boolean
      val barometer = pigeonVar_list[4] as Boolean
      return NativeSensorCapabilities(stepDetector, rotationVector, gyroscope, magnetometer, barometer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      stepDetector,
      rotationVector,
      gyroscope,
      magnetometer,
      barometer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSensorCapabilities
    return MessagesPigeonUtils.deepEquals(this.stepDetector, other.stepDetector) && MessagesPigeonUtils.deepEquals(this.rotationVector, other.rotationVector) && MessagesPigeonUtils.deepEquals(this.gyroscope, other.gyroscope) && MessagesPigeonUtils.deepEquals(this.magnetometer, other.magnetometer) && MessagesPigeonUtils.deepEquals(this.barometer, other.barometer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stepDetector)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationVector)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gyroscope)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.magnetometer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.barometer)
    return result
  }
  override fun toString(): String {
    return "NativeSensorCapabilities(stepDetector=$stepDetector, rotationVector=$rotationVector, gyroscope=$gyroscope, magnetometer=$magnetometer, barometer=$barometer)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeLocalPosition (
  val x: Double,
  val y: Double,
  val z: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLocalPosition {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val z = pigeonVar_list[2] as Double
      return NativeLocalPosition(x, y, z)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      z,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLocalPosition
    return MessagesPigeonUtils.deepEquals(this.x, other.x) && MessagesPigeonUtils.deepEquals(this.y, other.y) && MessagesPigeonUtils.deepEquals(this.z, other.z)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.x)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.y)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.z)
    return result
  }
  override fun toString(): String {
    return "NativeLocalPosition(x=$x, y=$y, z=$z)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeWgs84Position (
  val longitude: Double,
  val latitude: Double,
  val elevationM: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeWgs84Position {
      val longitude = pigeonVar_list[0] as Double
      val latitude = pigeonVar_list[1] as Double
      val elevationM = pigeonVar_list[2] as Double
      return NativeWgs84Position(longitude, latitude, elevationM)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      longitude,
      latitude,
      elevationM,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeWgs84Position
    return MessagesPigeonUtils.deepEquals(this.longitude, other.longitude) && MessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && MessagesPigeonUtils.deepEquals(this.elevationM, other.elevationM)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.elevationM)
    return result
  }
  override fun toString(): String {
    return "NativeWgs84Position(longitude=$longitude, latitude=$latitude, elevationM=$elevationM)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMotionHeadingReading (
  val localHeadingDeg: Double? = null,
  val magneticFieldAccuracy: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMotionHeadingReading {
      val localHeadingDeg = pigeonVar_list[0] as Double?
      val magneticFieldAccuracy = pigeonVar_list[1] as String?
      return NativeMotionHeadingReading(localHeadingDeg, magneticFieldAccuracy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      localHeadingDeg,
      magneticFieldAccuracy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMotionHeadingReading
    return MessagesPigeonUtils.deepEquals(this.localHeadingDeg, other.localHeadingDeg) && MessagesPigeonUtils.deepEquals(this.magneticFieldAccuracy, other.magneticFieldAccuracy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.localHeadingDeg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.magneticFieldAccuracy)
    return result
  }
  override fun toString(): String {
    return "NativeMotionHeadingReading(localHeadingDeg=$localHeadingDeg, magneticFieldAccuracy=$magneticFieldAccuracy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeBeaconSignalReading (
  val beaconId: String,
  val uuid: String,
  val major: Long,
  val minor: Long,
  val floorId: String,
  val rssiDbm: Double,
  val smoothedRssiDbm: Double,
  val radioDistanceM: Double,
  val configuredPosition: NativeLocalPosition,
  val configuredWgs84: NativeWgs84Position,
  val devicePosition: NativeLocalPosition? = null,
  val deviceWgs84: NativeWgs84Position? = null,
  val configuredDistanceM: Double? = null,
  val distanceDeltaM: Double? = null,
  val monotonicTimestampMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeBeaconSignalReading {
      val beaconId = pigeonVar_list[0] as String
      val uuid = pigeonVar_list[1] as String
      val major = pigeonVar_list[2] as Long
      val minor = pigeonVar_list[3] as Long
      val floorId = pigeonVar_list[4] as String
      val rssiDbm = pigeonVar_list[5] as Double
      val smoothedRssiDbm = pigeonVar_list[6] as Double
      val radioDistanceM = pigeonVar_list[7] as Double
      val configuredPosition = pigeonVar_list[8] as NativeLocalPosition
      val configuredWgs84 = pigeonVar_list[9] as NativeWgs84Position
      val devicePosition = pigeonVar_list[10] as NativeLocalPosition?
      val deviceWgs84 = pigeonVar_list[11] as NativeWgs84Position?
      val configuredDistanceM = pigeonVar_list[12] as Double?
      val distanceDeltaM = pigeonVar_list[13] as Double?
      val monotonicTimestampMs = pigeonVar_list[14] as Long
      return NativeBeaconSignalReading(beaconId, uuid, major, minor, floorId, rssiDbm, smoothedRssiDbm, radioDistanceM, configuredPosition, configuredWgs84, devicePosition, deviceWgs84, configuredDistanceM, distanceDeltaM, monotonicTimestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      beaconId,
      uuid,
      major,
      minor,
      floorId,
      rssiDbm,
      smoothedRssiDbm,
      radioDistanceM,
      configuredPosition,
      configuredWgs84,
      devicePosition,
      deviceWgs84,
      configuredDistanceM,
      distanceDeltaM,
      monotonicTimestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeBeaconSignalReading
    return MessagesPigeonUtils.deepEquals(this.beaconId, other.beaconId) && MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.major, other.major) && MessagesPigeonUtils.deepEquals(this.minor, other.minor) && MessagesPigeonUtils.deepEquals(this.floorId, other.floorId) && MessagesPigeonUtils.deepEquals(this.rssiDbm, other.rssiDbm) && MessagesPigeonUtils.deepEquals(this.smoothedRssiDbm, other.smoothedRssiDbm) && MessagesPigeonUtils.deepEquals(this.radioDistanceM, other.radioDistanceM) && MessagesPigeonUtils.deepEquals(this.configuredPosition, other.configuredPosition) && MessagesPigeonUtils.deepEquals(this.configuredWgs84, other.configuredWgs84) && MessagesPigeonUtils.deepEquals(this.devicePosition, other.devicePosition) && MessagesPigeonUtils.deepEquals(this.deviceWgs84, other.deviceWgs84) && MessagesPigeonUtils.deepEquals(this.configuredDistanceM, other.configuredDistanceM) && MessagesPigeonUtils.deepEquals(this.distanceDeltaM, other.distanceDeltaM) && MessagesPigeonUtils.deepEquals(this.monotonicTimestampMs, other.monotonicTimestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.beaconId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.major)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.minor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rssiDbm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.smoothedRssiDbm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.radioDistanceM)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.configuredPosition)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.configuredWgs84)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.devicePosition)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceWgs84)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.configuredDistanceM)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.distanceDeltaM)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.monotonicTimestampMs)
    return result
  }
  override fun toString(): String {
    return "NativeBeaconSignalReading(beaconId=$beaconId, uuid=$uuid, major=$major, minor=$minor, floorId=$floorId, rssiDbm=$rssiDbm, smoothedRssiDbm=$smoothedRssiDbm, radioDistanceM=$radioDistanceM, configuredPosition=$configuredPosition, configuredWgs84=$configuredWgs84, devicePosition=$devicePosition, deviceWgs84=$deviceWgs84, configuredDistanceM=$configuredDistanceM, distanceDeltaM=$distanceDeltaM, monotonicTimestampMs=$monotonicTimestampMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePositionEstimate (
  val sequence: Long,
  val monotonicTimestampMs: Long,
  val status: String,
  val mode: String,
  val floorId: String? = null,
  val floorProbability: Double,
  val local: NativeLocalPosition? = null,
  val accuracyRadiusM: Double,
  val headingDeg: Double? = null,
  val headingAccuracyDeg: Double? = null,
  val speedMps: Double,
  val freshBeaconCount: Long,
  val lastBleAgeMs: Long? = null,
  val manifestRevision: Long,
  val algorithmVersion: String,
  val stale: Boolean,
  val diagnosticFlags: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePositionEstimate {
      val sequence = pigeonVar_list[0] as Long
      val monotonicTimestampMs = pigeonVar_list[1] as Long
      val status = pigeonVar_list[2] as String
      val mode = pigeonVar_list[3] as String
      val floorId = pigeonVar_list[4] as String?
      val floorProbability = pigeonVar_list[5] as Double
      val local = pigeonVar_list[6] as NativeLocalPosition?
      val accuracyRadiusM = pigeonVar_list[7] as Double
      val headingDeg = pigeonVar_list[8] as Double?
      val headingAccuracyDeg = pigeonVar_list[9] as Double?
      val speedMps = pigeonVar_list[10] as Double
      val freshBeaconCount = pigeonVar_list[11] as Long
      val lastBleAgeMs = pigeonVar_list[12] as Long?
      val manifestRevision = pigeonVar_list[13] as Long
      val algorithmVersion = pigeonVar_list[14] as String
      val stale = pigeonVar_list[15] as Boolean
      val diagnosticFlags = pigeonVar_list[16] as List<String>
      return NativePositionEstimate(sequence, monotonicTimestampMs, status, mode, floorId, floorProbability, local, accuracyRadiusM, headingDeg, headingAccuracyDeg, speedMps, freshBeaconCount, lastBleAgeMs, manifestRevision, algorithmVersion, stale, diagnosticFlags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sequence,
      monotonicTimestampMs,
      status,
      mode,
      floorId,
      floorProbability,
      local,
      accuracyRadiusM,
      headingDeg,
      headingAccuracyDeg,
      speedMps,
      freshBeaconCount,
      lastBleAgeMs,
      manifestRevision,
      algorithmVersion,
      stale,
      diagnosticFlags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePositionEstimate
    return MessagesPigeonUtils.deepEquals(this.sequence, other.sequence) && MessagesPigeonUtils.deepEquals(this.monotonicTimestampMs, other.monotonicTimestampMs) && MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.mode, other.mode) && MessagesPigeonUtils.deepEquals(this.floorId, other.floorId) && MessagesPigeonUtils.deepEquals(this.floorProbability, other.floorProbability) && MessagesPigeonUtils.deepEquals(this.local, other.local) && MessagesPigeonUtils.deepEquals(this.accuracyRadiusM, other.accuracyRadiusM) && MessagesPigeonUtils.deepEquals(this.headingDeg, other.headingDeg) && MessagesPigeonUtils.deepEquals(this.headingAccuracyDeg, other.headingAccuracyDeg) && MessagesPigeonUtils.deepEquals(this.speedMps, other.speedMps) && MessagesPigeonUtils.deepEquals(this.freshBeaconCount, other.freshBeaconCount) && MessagesPigeonUtils.deepEquals(this.lastBleAgeMs, other.lastBleAgeMs) && MessagesPigeonUtils.deepEquals(this.manifestRevision, other.manifestRevision) && MessagesPigeonUtils.deepEquals(this.algorithmVersion, other.algorithmVersion) && MessagesPigeonUtils.deepEquals(this.stale, other.stale) && MessagesPigeonUtils.deepEquals(this.diagnosticFlags, other.diagnosticFlags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sequence)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.monotonicTimestampMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorProbability)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.local)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accuracyRadiusM)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headingDeg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headingAccuracyDeg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.speedMps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.freshBeaconCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lastBleAgeMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manifestRevision)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.algorithmVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stale)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.diagnosticFlags)
    return result
  }
  override fun toString(): String {
    return "NativePositionEstimate(sequence=$sequence, monotonicTimestampMs=$monotonicTimestampMs, status=$status, mode=$mode, floorId=$floorId, floorProbability=$floorProbability, local=$local, accuracyRadiusM=$accuracyRadiusM, headingDeg=$headingDeg, headingAccuracyDeg=$headingAccuracyDeg, speedMps=$speedMps, freshBeaconCount=$freshBeaconCount, lastBleAgeMs=$lastBleAgeMs, manifestRevision=$manifestRevision, algorithmVersion=$algorithmVersion, stale=$stale, diagnosticFlags=$diagnosticFlags)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePositioningUpdate (
  val mapId: String,
  val groupId: String,
  val estimate: NativePositionEstimate,
  val wgs84: NativeWgs84Position? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePositioningUpdate {
      val mapId = pigeonVar_list[0] as String
      val groupId = pigeonVar_list[1] as String
      val estimate = pigeonVar_list[2] as NativePositionEstimate
      val wgs84 = pigeonVar_list[3] as NativeWgs84Position?
      return NativePositioningUpdate(mapId, groupId, estimate, wgs84)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapId,
      groupId,
      estimate,
      wgs84,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePositioningUpdate
    return MessagesPigeonUtils.deepEquals(this.mapId, other.mapId) && MessagesPigeonUtils.deepEquals(this.groupId, other.groupId) && MessagesPigeonUtils.deepEquals(this.estimate, other.estimate) && MessagesPigeonUtils.deepEquals(this.wgs84, other.wgs84)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mapId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.groupId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.estimate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wgs84)
    return result
  }
  override fun toString(): String {
    return "NativePositioningUpdate(mapId=$mapId, groupId=$groupId, estimate=$estimate, wgs84=$wgs84)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeErrorMessage (
  val code: String,
  val message: String,
  val recoverable: Boolean,
  val userAction: String,
  val debugDetail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeErrorMessage {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val recoverable = pigeonVar_list[2] as Boolean
      val userAction = pigeonVar_list[3] as String
      val debugDetail = pigeonVar_list[4] as String?
      return NativeErrorMessage(code, message, recoverable, userAction, debugDetail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      recoverable,
      userAction,
      debugDetail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeErrorMessage
    return MessagesPigeonUtils.deepEquals(this.code, other.code) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.recoverable, other.recoverable) && MessagesPigeonUtils.deepEquals(this.userAction, other.userAction) && MessagesPigeonUtils.deepEquals(this.debugDetail, other.debugDetail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.recoverable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userAction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.debugDetail)
    return result
  }
  override fun toString(): String {
    return "NativeErrorMessage(code=$code, message=$message, recoverable=$recoverable, userAction=$userAction, debugDetail=$debugDetail)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapReadyEvent (
  val mapId: String,
  val groupId: String,
  val configRevision: String? = null,
  val manifestRevision: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapReadyEvent {
      val mapId = pigeonVar_list[0] as String
      val groupId = pigeonVar_list[1] as String
      val configRevision = pigeonVar_list[2] as String?
      val manifestRevision = pigeonVar_list[3] as Long?
      return NativeMapReadyEvent(mapId, groupId, configRevision, manifestRevision)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapId,
      groupId,
      configRevision,
      manifestRevision,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMapReadyEvent
    return MessagesPigeonUtils.deepEquals(this.mapId, other.mapId) && MessagesPigeonUtils.deepEquals(this.groupId, other.groupId) && MessagesPigeonUtils.deepEquals(this.configRevision, other.configRevision) && MessagesPigeonUtils.deepEquals(this.manifestRevision, other.manifestRevision)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mapId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.groupId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.configRevision)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manifestRevision)
    return result
  }
  override fun toString(): String {
    return "NativeMapReadyEvent(mapId=$mapId, groupId=$groupId, configRevision=$configRevision, manifestRevision=$manifestRevision)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeFloorChangedEvent (
  val floorId: String? = null,
  val source: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFloorChangedEvent {
      val floorId = pigeonVar_list[0] as String?
      val source = pigeonVar_list[1] as String?
      return NativeFloorChangedEvent(floorId, source)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      floorId,
      source,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeFloorChangedEvent
    return MessagesPigeonUtils.deepEquals(this.floorId, other.floorId) && MessagesPigeonUtils.deepEquals(this.source, other.source)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    return result
  }
  override fun toString(): String {
    return "NativeFloorChangedEvent(floorId=$floorId, source=$source)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeSpotSelectedEvent (
  val spotId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSpotSelectedEvent {
      val spotId = pigeonVar_list[0] as String?
      return NativeSpotSelectedEvent(spotId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      spotId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSpotSelectedEvent
    return MessagesPigeonUtils.deepEquals(this.spotId, other.spotId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.spotId)
    return result
  }
  override fun toString(): String {
    return "NativeSpotSelectedEvent(spotId=$spotId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRouteChangedEvent (
  val destinationSpotId: String? = null,
  val active: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRouteChangedEvent {
      val destinationSpotId = pigeonVar_list[0] as String?
      val active = pigeonVar_list[1] as Boolean
      return NativeRouteChangedEvent(destinationSpotId, active)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      destinationSpotId,
      active,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRouteChangedEvent
    return MessagesPigeonUtils.deepEquals(this.destinationSpotId, other.destinationSpotId) && MessagesPigeonUtils.deepEquals(this.active, other.active)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.destinationSpotId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.active)
    return result
  }
  override fun toString(): String {
    return "NativeRouteChangedEvent(destinationSpotId=$destinationSpotId, active=$active)"
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class NativeEvent
/** Generated class from Pigeon that represents data sent in messages. */
data class NativePositioningEvent (
  val clientId: Long,
  val type: String,
  val update: NativePositioningUpdate? = null,
  val status: String? = null,
  val capabilities: NativeCapabilityReport? = null,
  val motionHeading: NativeMotionHeadingReading? = null,
  val beaconSignals: List<NativeBeaconSignalReading>? = null,
  val error: NativeErrorMessage? = null
) : NativeEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePositioningEvent {
      val clientId = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as String
      val update = pigeonVar_list[2] as NativePositioningUpdate?
      val status = pigeonVar_list[3] as String?
      val capabilities = pigeonVar_list[4] as NativeCapabilityReport?
      val motionHeading = pigeonVar_list[5] as NativeMotionHeadingReading?
      val beaconSignals = pigeonVar_list[6] as List<NativeBeaconSignalReading>?
      val error = pigeonVar_list[7] as NativeErrorMessage?
      return NativePositioningEvent(clientId, type, update, status, capabilities, motionHeading, beaconSignals, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      type,
      update,
      status,
      capabilities,
      motionHeading,
      beaconSignals,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePositioningEvent
    return MessagesPigeonUtils.deepEquals(this.clientId, other.clientId) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.update, other.update) && MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.capabilities, other.capabilities) && MessagesPigeonUtils.deepEquals(this.motionHeading, other.motionHeading) && MessagesPigeonUtils.deepEquals(this.beaconSignals, other.beaconSignals) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.update)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.capabilities)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.motionHeading)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.beaconSignals)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativePositioningEvent(clientId=$clientId, type=$type, update=$update, status=$status, capabilities=$capabilities, motionHeading=$motionHeading, beaconSignals=$beaconSignals, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapViewEvent (
  val viewId: Long,
  val type: String,
  val ready: NativeMapReadyEvent? = null,
  val loadState: String? = null,
  val positioningStatus: String? = null,
  val position: NativePositioningUpdate? = null,
  val capabilities: NativeCapabilityReport? = null,
  val motionHeading: NativeMotionHeadingReading? = null,
  val beaconSignals: List<NativeBeaconSignalReading>? = null,
  val floorChanged: NativeFloorChangedEvent? = null,
  val spotSelected: NativeSpotSelectedEvent? = null,
  val routeChanged: NativeRouteChangedEvent? = null,
  val externalUrl: String? = null,
  val error: NativeErrorMessage? = null
) : NativeEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapViewEvent {
      val viewId = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as String
      val ready = pigeonVar_list[2] as NativeMapReadyEvent?
      val loadState = pigeonVar_list[3] as String?
      val positioningStatus = pigeonVar_list[4] as String?
      val position = pigeonVar_list[5] as NativePositioningUpdate?
      val capabilities = pigeonVar_list[6] as NativeCapabilityReport?
      val motionHeading = pigeonVar_list[7] as NativeMotionHeadingReading?
      val beaconSignals = pigeonVar_list[8] as List<NativeBeaconSignalReading>?
      val floorChanged = pigeonVar_list[9] as NativeFloorChangedEvent?
      val spotSelected = pigeonVar_list[10] as NativeSpotSelectedEvent?
      val routeChanged = pigeonVar_list[11] as NativeRouteChangedEvent?
      val externalUrl = pigeonVar_list[12] as String?
      val error = pigeonVar_list[13] as NativeErrorMessage?
      return NativeMapViewEvent(viewId, type, ready, loadState, positioningStatus, position, capabilities, motionHeading, beaconSignals, floorChanged, spotSelected, routeChanged, externalUrl, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewId,
      type,
      ready,
      loadState,
      positioningStatus,
      position,
      capabilities,
      motionHeading,
      beaconSignals,
      floorChanged,
      spotSelected,
      routeChanged,
      externalUrl,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMapViewEvent
    return MessagesPigeonUtils.deepEquals(this.viewId, other.viewId) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.ready, other.ready) && MessagesPigeonUtils.deepEquals(this.loadState, other.loadState) && MessagesPigeonUtils.deepEquals(this.positioningStatus, other.positioningStatus) && MessagesPigeonUtils.deepEquals(this.position, other.position) && MessagesPigeonUtils.deepEquals(this.capabilities, other.capabilities) && MessagesPigeonUtils.deepEquals(this.motionHeading, other.motionHeading) && MessagesPigeonUtils.deepEquals(this.beaconSignals, other.beaconSignals) && MessagesPigeonUtils.deepEquals(this.floorChanged, other.floorChanged) && MessagesPigeonUtils.deepEquals(this.spotSelected, other.spotSelected) && MessagesPigeonUtils.deepEquals(this.routeChanged, other.routeChanged) && MessagesPigeonUtils.deepEquals(this.externalUrl, other.externalUrl) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.viewId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ready)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.loadState)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positioningStatus)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.position)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.capabilities)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.motionHeading)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.beaconSignals)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.floorChanged)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.spotSelected)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeChanged)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.externalUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeMapViewEvent(viewId=$viewId, type=$type, ready=$ready, loadState=$loadState, positioningStatus=$positioningStatus, position=$position, capabilities=$capabilities, motionHeading=$motionHeading, beaconSignals=$beaconSignals, floorChanged=$floorChanged, spotSelected=$spotSelected, routeChanged=$routeChanged, externalUrl=$externalUrl, error=$error)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePositioningConfiguration.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeOperationResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeClientCreateResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCapabilityResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapCenterReticleCandidateResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapCenterReticleCandidate.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCapabilityReport.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeBleCapabilities.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAuthorizationCapabilities.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSensorCapabilities.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLocalPosition.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeWgs84Position.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMotionHeadingReading.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeBeaconSignalReading.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePositionEstimate.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePositioningUpdate.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeErrorMessage.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapReadyEvent.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFloorChangedEvent.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSpotSelectedEvent.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRouteChangedEvent.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePositioningEvent.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapViewEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativePositioningConfiguration -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeOperationResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeClientCreateResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeCapabilityResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeMapCenterReticleCandidateResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeMapCenterReticleCandidate -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeCapabilityReport -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeBleCapabilities -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NativeAuthorizationCapabilities -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is NativeSensorCapabilities -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is NativeLocalPosition -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is NativeWgs84Position -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is NativeMotionHeadingReading -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is NativeBeaconSignalReading -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is NativePositionEstimate -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is NativePositioningUpdate -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is NativeErrorMessage -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is NativeMapReadyEvent -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is NativeFloorChangedEvent -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is NativeSpotSelectedEvent -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is NativeRouteChangedEvent -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is NativePositioningEvent -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is NativeMapViewEvent -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MetamapsHostApi {
  fun createClient(configuration: NativePositioningConfiguration, callback: (Result<NativeClientCreateResult>) -> Unit)
  fun configureClient(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun clientCapabilities(clientId: Long, callback: (Result<NativeCapabilityResult>) -> Unit)
  fun requestClientAuthorization(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun startClient(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun stopClient(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun resetClient(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun resetClientPedestrianRoute(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun disposeClient(clientId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun loadMapView(viewId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun reloadMapView(viewId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun requestMapViewAuthorization(viewId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun startMapViewPositioning(viewId: Long, requestAuthorization: Boolean, callback: (Result<NativeOperationResult>) -> Unit)
  fun stopMapViewPositioning(viewId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun resetMapViewPedestrianRoute(viewId: Long, callback: (Result<NativeOperationResult>) -> Unit)
  fun selectMapViewFloor(viewId: Long, floorId: String?, callback: (Result<NativeOperationResult>) -> Unit)
  fun showMapViewSpot(viewId: Long, spotId: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun setMapViewDestination(viewId: Long, spotId: String?, callback: (Result<NativeOperationResult>) -> Unit)
  fun setMapViewLanguage(viewId: Long, language: String, callback: (Result<NativeOperationResult>) -> Unit)
  fun setMapViewCenterReticleEnabled(viewId: Long, enabled: Boolean, callback: (Result<NativeOperationResult>) -> Unit)
  fun requestMapViewCenterReticleCandidate(viewId: Long, callback: (Result<NativeMapCenterReticleCandidateResult>) -> Unit)
  fun openMapViewExternalLink(viewId: Long, url: String, callback: (Result<NativeOperationResult>) -> Unit)

  companion object {
    /** The codec used by MetamapsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MetamapsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MetamapsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.createClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as NativePositioningConfiguration
            api.createClient(configurationArg) { result: Result<NativeClientCreateResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.configureClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.configureClient(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.clientCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.clientCapabilities(clientIdArg) { result: Result<NativeCapabilityResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestClientAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.requestClientAuthorization(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.startClient(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.stopClient(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.resetClient(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClientPedestrianRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.resetClientPedestrianRoute(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.disposeClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.disposeClient(clientIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.loadMapView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.loadMapView(viewIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.reloadMapView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.reloadMapView(viewIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.requestMapViewAuthorization(viewIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startMapViewPositioning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val requestAuthorizationArg = args[1] as Boolean
            api.startMapViewPositioning(viewIdArg, requestAuthorizationArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopMapViewPositioning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.stopMapViewPositioning(viewIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetMapViewPedestrianRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.resetMapViewPedestrianRoute(viewIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.selectMapViewFloor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val floorIdArg = args[1] as String?
            api.selectMapViewFloor(viewIdArg, floorIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.showMapViewSpot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val spotIdArg = args[1] as String
            api.showMapViewSpot(viewIdArg, spotIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val spotIdArg = args[1] as String?
            api.setMapViewDestination(viewIdArg, spotIdArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewLanguage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val languageArg = args[1] as String
            api.setMapViewLanguage(viewIdArg, languageArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewCenterReticleEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val enabledArg = args[1] as Boolean
            api.setMapViewCenterReticleEnabled(viewIdArg, enabledArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewCenterReticleCandidate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            api.requestMapViewCenterReticleCandidate(viewIdArg) { result: Result<NativeMapCenterReticleCandidateResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.openMapViewExternalLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.openMapViewExternalLink(viewIdArg, urlArg) { result: Result<NativeOperationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MetamapsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MetamapsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun decideMapViewExternalLinkOpensDefault(viewIdArg: Long, urlArg: String, callback: (Result<Boolean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.metamaps_flutter.MetamapsFlutterApi.decideMapViewExternalLinkOpensDefault$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(viewIdArg, urlArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Boolean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}

abstract class EventsStreamHandler : MessagesPigeonEventChannelWrapper<NativeEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.metamaps_flutter.MetamapsEventChannel.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<NativeEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NativeEvent>) {}

override fun onCancel(p0: Any?) {}
}
