{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.metamaps.positioning",
    "module": "metamap-positioning",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.metamaps.positioning",
          "module": "metamap-positioning-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-0.5.0.aar",
          "url": "metamap-positioning-0.5.0.aar",
          "size": 192031,
          "sha512": "1a801be6e20239718b3908e117acd0bd4df191cd4a3c24e78bb18bf8ed1ea87d2c3e9f4e47356bb53f9e59ea1c302cf7ac91aba4e67efeb23a16cb0efb359224",
          "sha256": "355d2f3a08dca55b0169864710d30264522b89e68412fbe1004cb05474476866",
          "sha1": "ab0d760daf717584ca59b363e95d847a0b2d8f54",
          "md5": "f2486d58c1c2b4167536a51824e13cb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.2"
          }
        },
        {
          "group": "jp.metamaps.positioning",
          "module": "metamap-positioning-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-0.5.0.aar",
          "url": "metamap-positioning-0.5.0.aar",
          "size": 192031,
          "sha512": "1a801be6e20239718b3908e117acd0bd4df191cd4a3c24e78bb18bf8ed1ea87d2c3e9f4e47356bb53f9e59ea1c302cf7ac91aba4e67efeb23a16cb0efb359224",
          "sha256": "355d2f3a08dca55b0169864710d30264522b89e68412fbe1004cb05474476866",
          "sha1": "ab0d760daf717584ca59b363e95d847a0b2d8f54",
          "md5": "f2486d58c1c2b4167536a51824e13cb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "metamap-positioning-0.5.0-sources.jar",
          "url": "metamap-positioning-0.5.0-sources.jar",
          "size": 28825,
          "sha512": "fc8f3672c0f36e34441519ace247acd397c0ab1edb0ec31e4ab26300f06b9ad144bff71b1e5960c3b8e9e9e6737e03f73040ae5bb54b18a479653b9211e35181",
          "sha256": "affeff66824a0b1a307b2c40b31e3134ad191c72c4aaf7a741b25f7596f0a386",
          "sha1": "88db0da923bb2e572060b30f4584fd81b1c3d89b",
          "md5": "2569f363af3c27e2645f3220f6eebcff"
        }
      ]
    }
  ]
}
