// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativePositioningConfiguration: Hashable, CustomStringConvertible {
  var baseUrl: String
  var mapSlug: String
  var groupId: String? = nil
  var maxOfflineAgeMs: Int64
  var motionPolicy: String
  var beaconDiagnosticsEnabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePositioningConfiguration? {
    let baseUrl = pigeonVar_list[0] as! String
    let mapSlug = pigeonVar_list[1] as! String
    let groupId: String? = nilOrValue(pigeonVar_list[2])
    let maxOfflineAgeMs = pigeonVar_list[3] as! Int64
    let motionPolicy = pigeonVar_list[4] as! String
    let beaconDiagnosticsEnabled = pigeonVar_list[5] as! Bool

    return NativePositioningConfiguration(
      baseUrl: baseUrl,
      mapSlug: mapSlug,
      groupId: groupId,
      maxOfflineAgeMs: maxOfflineAgeMs,
      motionPolicy: motionPolicy,
      beaconDiagnosticsEnabled: beaconDiagnosticsEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      mapSlug,
      groupId,
      maxOfflineAgeMs,
      motionPolicy,
      beaconDiagnosticsEnabled,
    ]
  }
  static func == (lhs: NativePositioningConfiguration, rhs: NativePositioningConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.baseUrl, rhs.baseUrl) && MessagesPigeonInternal.deepEquals(lhs.mapSlug, rhs.mapSlug) && MessagesPigeonInternal.deepEquals(lhs.groupId, rhs.groupId) && MessagesPigeonInternal.deepEquals(lhs.maxOfflineAgeMs, rhs.maxOfflineAgeMs) && MessagesPigeonInternal.deepEquals(lhs.motionPolicy, rhs.motionPolicy) && MessagesPigeonInternal.deepEquals(lhs.beaconDiagnosticsEnabled, rhs.beaconDiagnosticsEnabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePositioningConfiguration")
    MessagesPigeonInternal.deepHash(value: baseUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mapSlug, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: groupId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxOfflineAgeMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: motionPolicy, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: beaconDiagnosticsEnabled, hasher: &hasher)
  }

  public var description: String {
    return "NativePositioningConfiguration(baseUrl: \(String(describing: baseUrl)), mapSlug: \(String(describing: mapSlug)), groupId: \(String(describing: groupId)), maxOfflineAgeMs: \(String(describing: maxOfflineAgeMs)), motionPolicy: \(String(describing: motionPolicy)), beaconDiagnosticsEnabled: \(String(describing: beaconDiagnosticsEnabled)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeOperationResult: Hashable, CustomStringConvertible {
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeOperationResult? {
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[0])

    return NativeOperationResult(
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      error
    ]
  }
  static func == (lhs: NativeOperationResult, rhs: NativeOperationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeOperationResult")
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeOperationResult(error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeClientCreateResult: Hashable, CustomStringConvertible {
  var clientId: Int64? = nil
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeClientCreateResult? {
    let clientId: Int64? = nilOrValue(pigeonVar_list[0])
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[1])

    return NativeClientCreateResult(
      clientId: clientId,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      error,
    ]
  }
  static func == (lhs: NativeClientCreateResult, rhs: NativeClientCreateResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeClientCreateResult")
    MessagesPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeClientCreateResult(clientId: \(String(describing: clientId)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCapabilityResult: Hashable, CustomStringConvertible {
  var report: NativeCapabilityReport? = nil
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCapabilityResult? {
    let report: NativeCapabilityReport? = nilOrValue(pigeonVar_list[0])
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[1])

    return NativeCapabilityResult(
      report: report,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      report,
      error,
    ]
  }
  static func == (lhs: NativeCapabilityResult, rhs: NativeCapabilityResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.report, rhs.report) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCapabilityResult")
    MessagesPigeonInternal.deepHash(value: report, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeCapabilityResult(report: \(String(describing: report)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapCenterReticleCandidateResult: Hashable, CustomStringConvertible {
  var candidate: NativeMapCenterReticleCandidate? = nil
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapCenterReticleCandidateResult? {
    let candidate: NativeMapCenterReticleCandidate? = nilOrValue(pigeonVar_list[0])
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[1])

    return NativeMapCenterReticleCandidateResult(
      candidate: candidate,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      candidate,
      error,
    ]
  }
  static func == (lhs: NativeMapCenterReticleCandidateResult, rhs: NativeMapCenterReticleCandidateResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.candidate, rhs.candidate) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMapCenterReticleCandidateResult")
    MessagesPigeonInternal.deepHash(value: candidate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeMapCenterReticleCandidateResult(candidate: \(String(describing: candidate)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapCenterReticleCandidate: Hashable, CustomStringConvertible {
  var floorId: String
  var longitude: Double
  var latitude: Double
  var local: NativeLocalPosition? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapCenterReticleCandidate? {
    let floorId = pigeonVar_list[0] as! String
    let longitude = pigeonVar_list[1] as! Double
    let latitude = pigeonVar_list[2] as! Double
    let local: NativeLocalPosition? = nilOrValue(pigeonVar_list[3])

    return NativeMapCenterReticleCandidate(
      floorId: floorId,
      longitude: longitude,
      latitude: latitude,
      local: local
    )
  }
  func toList() -> [Any?] {
    return [
      floorId,
      longitude,
      latitude,
      local,
    ]
  }
  static func == (lhs: NativeMapCenterReticleCandidate, rhs: NativeMapCenterReticleCandidate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.floorId, rhs.floorId) && MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.local, rhs.local)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMapCenterReticleCandidate")
    MessagesPigeonInternal.deepHash(value: floorId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: local, hasher: &hasher)
  }

  public var description: String {
    return "NativeMapCenterReticleCandidate(floorId: \(String(describing: floorId)), longitude: \(String(describing: longitude)), latitude: \(String(describing: latitude)), local: \(String(describing: local)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCapabilityReport: Hashable, CustomStringConvertible {
  var platform: String
  var osVersion: String
  var sdkVersion: String
  var ble: NativeBleCapabilities
  var authorization: NativeAuthorizationCapabilities
  var sensors: NativeSensorCapabilities
  var selectedProfile: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCapabilityReport? {
    let platform = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let sdkVersion = pigeonVar_list[2] as! String
    let ble = pigeonVar_list[3] as! NativeBleCapabilities
    let authorization = pigeonVar_list[4] as! NativeAuthorizationCapabilities
    let sensors = pigeonVar_list[5] as! NativeSensorCapabilities
    let selectedProfile = pigeonVar_list[6] as! String

    return NativeCapabilityReport(
      platform: platform,
      osVersion: osVersion,
      sdkVersion: sdkVersion,
      ble: ble,
      authorization: authorization,
      sensors: sensors,
      selectedProfile: selectedProfile
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      osVersion,
      sdkVersion,
      ble,
      authorization,
      sensors,
      selectedProfile,
    ]
  }
  static func == (lhs: NativeCapabilityReport, rhs: NativeCapabilityReport) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && MessagesPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && MessagesPigeonInternal.deepEquals(lhs.sdkVersion, rhs.sdkVersion) && MessagesPigeonInternal.deepEquals(lhs.ble, rhs.ble) && MessagesPigeonInternal.deepEquals(lhs.authorization, rhs.authorization) && MessagesPigeonInternal.deepEquals(lhs.sensors, rhs.sensors) && MessagesPigeonInternal.deepEquals(lhs.selectedProfile, rhs.selectedProfile)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCapabilityReport")
    MessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sdkVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ble, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: authorization, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sensors, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedProfile, hasher: &hasher)
  }

  public var description: String {
    return "NativeCapabilityReport(platform: \(String(describing: platform)), osVersion: \(String(describing: osVersion)), sdkVersion: \(String(describing: sdkVersion)), ble: \(String(describing: ble)), authorization: \(String(describing: authorization)), sensors: \(String(describing: sensors)), selectedProfile: \(String(describing: selectedProfile)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeBleCapabilities: Hashable, CustomStringConvertible {
  var supported: Bool
  var enabled: Bool
  var rangingAvailable: Bool
  var foregroundScan: Bool
  var backgroundScan: String
  var directionFinding: String
  var channelSounding: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeBleCapabilities? {
    let supported = pigeonVar_list[0] as! Bool
    let enabled = pigeonVar_list[1] as! Bool
    let rangingAvailable = pigeonVar_list[2] as! Bool
    let foregroundScan = pigeonVar_list[3] as! Bool
    let backgroundScan = pigeonVar_list[4] as! String
    let directionFinding = pigeonVar_list[5] as! String
    let channelSounding = pigeonVar_list[6] as! String

    return NativeBleCapabilities(
      supported: supported,
      enabled: enabled,
      rangingAvailable: rangingAvailable,
      foregroundScan: foregroundScan,
      backgroundScan: backgroundScan,
      directionFinding: directionFinding,
      channelSounding: channelSounding
    )
  }
  func toList() -> [Any?] {
    return [
      supported,
      enabled,
      rangingAvailable,
      foregroundScan,
      backgroundScan,
      directionFinding,
      channelSounding,
    ]
  }
  static func == (lhs: NativeBleCapabilities, rhs: NativeBleCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.supported, rhs.supported) && MessagesPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MessagesPigeonInternal.deepEquals(lhs.rangingAvailable, rhs.rangingAvailable) && MessagesPigeonInternal.deepEquals(lhs.foregroundScan, rhs.foregroundScan) && MessagesPigeonInternal.deepEquals(lhs.backgroundScan, rhs.backgroundScan) && MessagesPigeonInternal.deepEquals(lhs.directionFinding, rhs.directionFinding) && MessagesPigeonInternal.deepEquals(lhs.channelSounding, rhs.channelSounding)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeBleCapabilities")
    MessagesPigeonInternal.deepHash(value: supported, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rangingAvailable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: foregroundScan, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: backgroundScan, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: directionFinding, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channelSounding, hasher: &hasher)
  }

  public var description: String {
    return "NativeBleCapabilities(supported: \(String(describing: supported)), enabled: \(String(describing: enabled)), rangingAvailable: \(String(describing: rangingAvailable)), foregroundScan: \(String(describing: foregroundScan)), backgroundScan: \(String(describing: backgroundScan)), directionFinding: \(String(describing: directionFinding)), channelSounding: \(String(describing: channelSounding)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAuthorizationCapabilities: Hashable, CustomStringConvertible {
  var location: String
  var preciseLocation: Bool
  var bluetoothScan: String
  var motion: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAuthorizationCapabilities? {
    let location = pigeonVar_list[0] as! String
    let preciseLocation = pigeonVar_list[1] as! Bool
    let bluetoothScan = pigeonVar_list[2] as! String
    let motion = pigeonVar_list[3] as! String

    return NativeAuthorizationCapabilities(
      location: location,
      preciseLocation: preciseLocation,
      bluetoothScan: bluetoothScan,
      motion: motion
    )
  }
  func toList() -> [Any?] {
    return [
      location,
      preciseLocation,
      bluetoothScan,
      motion,
    ]
  }
  static func == (lhs: NativeAuthorizationCapabilities, rhs: NativeAuthorizationCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.location, rhs.location) && MessagesPigeonInternal.deepEquals(lhs.preciseLocation, rhs.preciseLocation) && MessagesPigeonInternal.deepEquals(lhs.bluetoothScan, rhs.bluetoothScan) && MessagesPigeonInternal.deepEquals(lhs.motion, rhs.motion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAuthorizationCapabilities")
    MessagesPigeonInternal.deepHash(value: location, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: preciseLocation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bluetoothScan, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: motion, hasher: &hasher)
  }

  public var description: String {
    return "NativeAuthorizationCapabilities(location: \(String(describing: location)), preciseLocation: \(String(describing: preciseLocation)), bluetoothScan: \(String(describing: bluetoothScan)), motion: \(String(describing: motion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeSensorCapabilities: Hashable, CustomStringConvertible {
  var stepDetector: Bool
  var rotationVector: Bool
  var gyroscope: Bool
  var magnetometer: Bool
  var barometer: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSensorCapabilities? {
    let stepDetector = pigeonVar_list[0] as! Bool
    let rotationVector = pigeonVar_list[1] as! Bool
    let gyroscope = pigeonVar_list[2] as! Bool
    let magnetometer = pigeonVar_list[3] as! Bool
    let barometer = pigeonVar_list[4] as! Bool

    return NativeSensorCapabilities(
      stepDetector: stepDetector,
      rotationVector: rotationVector,
      gyroscope: gyroscope,
      magnetometer: magnetometer,
      barometer: barometer
    )
  }
  func toList() -> [Any?] {
    return [
      stepDetector,
      rotationVector,
      gyroscope,
      magnetometer,
      barometer,
    ]
  }
  static func == (lhs: NativeSensorCapabilities, rhs: NativeSensorCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.stepDetector, rhs.stepDetector) && MessagesPigeonInternal.deepEquals(lhs.rotationVector, rhs.rotationVector) && MessagesPigeonInternal.deepEquals(lhs.gyroscope, rhs.gyroscope) && MessagesPigeonInternal.deepEquals(lhs.magnetometer, rhs.magnetometer) && MessagesPigeonInternal.deepEquals(lhs.barometer, rhs.barometer)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSensorCapabilities")
    MessagesPigeonInternal.deepHash(value: stepDetector, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationVector, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gyroscope, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: magnetometer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: barometer, hasher: &hasher)
  }

  public var description: String {
    return "NativeSensorCapabilities(stepDetector: \(String(describing: stepDetector)), rotationVector: \(String(describing: rotationVector)), gyroscope: \(String(describing: gyroscope)), magnetometer: \(String(describing: magnetometer)), barometer: \(String(describing: barometer)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLocalPosition: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var z: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLocalPosition? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let z = pigeonVar_list[2] as! Double

    return NativeLocalPosition(
      x: x,
      y: y,
      z: z
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      z,
    ]
  }
  static func == (lhs: NativeLocalPosition, rhs: NativeLocalPosition) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y) && MessagesPigeonInternal.deepEquals(lhs.z, rhs.z)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLocalPosition")
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: z, hasher: &hasher)
  }

  public var description: String {
    return "NativeLocalPosition(x: \(String(describing: x)), y: \(String(describing: y)), z: \(String(describing: z)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeWgs84Position: Hashable, CustomStringConvertible {
  var longitude: Double
  var latitude: Double
  var elevationM: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeWgs84Position? {
    let longitude = pigeonVar_list[0] as! Double
    let latitude = pigeonVar_list[1] as! Double
    let elevationM = pigeonVar_list[2] as! Double

    return NativeWgs84Position(
      longitude: longitude,
      latitude: latitude,
      elevationM: elevationM
    )
  }
  func toList() -> [Any?] {
    return [
      longitude,
      latitude,
      elevationM,
    ]
  }
  static func == (lhs: NativeWgs84Position, rhs: NativeWgs84Position) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.elevationM, rhs.elevationM)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeWgs84Position")
    MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: elevationM, hasher: &hasher)
  }

  public var description: String {
    return "NativeWgs84Position(longitude: \(String(describing: longitude)), latitude: \(String(describing: latitude)), elevationM: \(String(describing: elevationM)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMotionHeadingReading: Hashable, CustomStringConvertible {
  var localHeadingDeg: Double? = nil
  var magneticFieldAccuracy: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMotionHeadingReading? {
    let localHeadingDeg: Double? = nilOrValue(pigeonVar_list[0])
    let magneticFieldAccuracy: String? = nilOrValue(pigeonVar_list[1])

    return NativeMotionHeadingReading(
      localHeadingDeg: localHeadingDeg,
      magneticFieldAccuracy: magneticFieldAccuracy
    )
  }
  func toList() -> [Any?] {
    return [
      localHeadingDeg,
      magneticFieldAccuracy,
    ]
  }
  static func == (lhs: NativeMotionHeadingReading, rhs: NativeMotionHeadingReading) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.localHeadingDeg, rhs.localHeadingDeg) && MessagesPigeonInternal.deepEquals(lhs.magneticFieldAccuracy, rhs.magneticFieldAccuracy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMotionHeadingReading")
    MessagesPigeonInternal.deepHash(value: localHeadingDeg, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: magneticFieldAccuracy, hasher: &hasher)
  }

  public var description: String {
    return "NativeMotionHeadingReading(localHeadingDeg: \(String(describing: localHeadingDeg)), magneticFieldAccuracy: \(String(describing: magneticFieldAccuracy)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeBeaconSignalReading: Hashable, CustomStringConvertible {
  var beaconId: String
  var uuid: String
  var major: Int64
  var minor: Int64
  var floorId: String
  var rssiDbm: Double
  var smoothedRssiDbm: Double
  var radioDistanceM: Double
  var configuredPosition: NativeLocalPosition
  var configuredWgs84: NativeWgs84Position
  var devicePosition: NativeLocalPosition? = nil
  var deviceWgs84: NativeWgs84Position? = nil
  var configuredDistanceM: Double? = nil
  var distanceDeltaM: Double? = nil
  var monotonicTimestampMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeBeaconSignalReading? {
    let beaconId = pigeonVar_list[0] as! String
    let uuid = pigeonVar_list[1] as! String
    let major = pigeonVar_list[2] as! Int64
    let minor = pigeonVar_list[3] as! Int64
    let floorId = pigeonVar_list[4] as! String
    let rssiDbm = pigeonVar_list[5] as! Double
    let smoothedRssiDbm = pigeonVar_list[6] as! Double
    let radioDistanceM = pigeonVar_list[7] as! Double
    let configuredPosition = pigeonVar_list[8] as! NativeLocalPosition
    let configuredWgs84 = pigeonVar_list[9] as! NativeWgs84Position
    let devicePosition: NativeLocalPosition? = nilOrValue(pigeonVar_list[10])
    let deviceWgs84: NativeWgs84Position? = nilOrValue(pigeonVar_list[11])
    let configuredDistanceM: Double? = nilOrValue(pigeonVar_list[12])
    let distanceDeltaM: Double? = nilOrValue(pigeonVar_list[13])
    let monotonicTimestampMs = pigeonVar_list[14] as! Int64

    return NativeBeaconSignalReading(
      beaconId: beaconId,
      uuid: uuid,
      major: major,
      minor: minor,
      floorId: floorId,
      rssiDbm: rssiDbm,
      smoothedRssiDbm: smoothedRssiDbm,
      radioDistanceM: radioDistanceM,
      configuredPosition: configuredPosition,
      configuredWgs84: configuredWgs84,
      devicePosition: devicePosition,
      deviceWgs84: deviceWgs84,
      configuredDistanceM: configuredDistanceM,
      distanceDeltaM: distanceDeltaM,
      monotonicTimestampMs: monotonicTimestampMs
    )
  }
  func toList() -> [Any?] {
    return [
      beaconId,
      uuid,
      major,
      minor,
      floorId,
      rssiDbm,
      smoothedRssiDbm,
      radioDistanceM,
      configuredPosition,
      configuredWgs84,
      devicePosition,
      deviceWgs84,
      configuredDistanceM,
      distanceDeltaM,
      monotonicTimestampMs,
    ]
  }
  static func == (lhs: NativeBeaconSignalReading, rhs: NativeBeaconSignalReading) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.beaconId, rhs.beaconId) && MessagesPigeonInternal.deepEquals(lhs.uuid, rhs.uuid) && MessagesPigeonInternal.deepEquals(lhs.major, rhs.major) && MessagesPigeonInternal.deepEquals(lhs.minor, rhs.minor) && MessagesPigeonInternal.deepEquals(lhs.floorId, rhs.floorId) && MessagesPigeonInternal.deepEquals(lhs.rssiDbm, rhs.rssiDbm) && MessagesPigeonInternal.deepEquals(lhs.smoothedRssiDbm, rhs.smoothedRssiDbm) && MessagesPigeonInternal.deepEquals(lhs.radioDistanceM, rhs.radioDistanceM) && MessagesPigeonInternal.deepEquals(lhs.configuredPosition, rhs.configuredPosition) && MessagesPigeonInternal.deepEquals(lhs.configuredWgs84, rhs.configuredWgs84) && MessagesPigeonInternal.deepEquals(lhs.devicePosition, rhs.devicePosition) && MessagesPigeonInternal.deepEquals(lhs.deviceWgs84, rhs.deviceWgs84) && MessagesPigeonInternal.deepEquals(lhs.configuredDistanceM, rhs.configuredDistanceM) && MessagesPigeonInternal.deepEquals(lhs.distanceDeltaM, rhs.distanceDeltaM) && MessagesPigeonInternal.deepEquals(lhs.monotonicTimestampMs, rhs.monotonicTimestampMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeBeaconSignalReading")
    MessagesPigeonInternal.deepHash(value: beaconId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uuid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: major, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: floorId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rssiDbm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: smoothedRssiDbm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: radioDistanceM, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configuredPosition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configuredWgs84, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: devicePosition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceWgs84, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configuredDistanceM, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: distanceDeltaM, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: monotonicTimestampMs, hasher: &hasher)
  }

  public var description: String {
    return "NativeBeaconSignalReading(beaconId: \(String(describing: beaconId)), uuid: \(String(describing: uuid)), major: \(String(describing: major)), minor: \(String(describing: minor)), floorId: \(String(describing: floorId)), rssiDbm: \(String(describing: rssiDbm)), smoothedRssiDbm: \(String(describing: smoothedRssiDbm)), radioDistanceM: \(String(describing: radioDistanceM)), configuredPosition: \(String(describing: configuredPosition)), configuredWgs84: \(String(describing: configuredWgs84)), devicePosition: \(String(describing: devicePosition)), deviceWgs84: \(String(describing: deviceWgs84)), configuredDistanceM: \(String(describing: configuredDistanceM)), distanceDeltaM: \(String(describing: distanceDeltaM)), monotonicTimestampMs: \(String(describing: monotonicTimestampMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePositionEstimate: Hashable, CustomStringConvertible {
  var sequence: Int64
  var monotonicTimestampMs: Int64
  var status: String
  var mode: String
  var floorId: String? = nil
  var floorProbability: Double
  var local: NativeLocalPosition? = nil
  var accuracyRadiusM: Double
  var headingDeg: Double? = nil
  var headingAccuracyDeg: Double? = nil
  var speedMps: Double
  var freshBeaconCount: Int64
  var lastBleAgeMs: Int64? = nil
  var manifestRevision: Int64
  var algorithmVersion: String
  var stale: Bool
  var diagnosticFlags: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePositionEstimate? {
    let sequence = pigeonVar_list[0] as! Int64
    let monotonicTimestampMs = pigeonVar_list[1] as! Int64
    let status = pigeonVar_list[2] as! String
    let mode = pigeonVar_list[3] as! String
    let floorId: String? = nilOrValue(pigeonVar_list[4])
    let floorProbability = pigeonVar_list[5] as! Double
    let local: NativeLocalPosition? = nilOrValue(pigeonVar_list[6])
    let accuracyRadiusM = pigeonVar_list[7] as! Double
    let headingDeg: Double? = nilOrValue(pigeonVar_list[8])
    let headingAccuracyDeg: Double? = nilOrValue(pigeonVar_list[9])
    let speedMps = pigeonVar_list[10] as! Double
    let freshBeaconCount = pigeonVar_list[11] as! Int64
    let lastBleAgeMs: Int64? = nilOrValue(pigeonVar_list[12])
    let manifestRevision = pigeonVar_list[13] as! Int64
    let algorithmVersion = pigeonVar_list[14] as! String
    let stale = pigeonVar_list[15] as! Bool
    let diagnosticFlags = pigeonVar_list[16] as! [String]

    return NativePositionEstimate(
      sequence: sequence,
      monotonicTimestampMs: monotonicTimestampMs,
      status: status,
      mode: mode,
      floorId: floorId,
      floorProbability: floorProbability,
      local: local,
      accuracyRadiusM: accuracyRadiusM,
      headingDeg: headingDeg,
      headingAccuracyDeg: headingAccuracyDeg,
      speedMps: speedMps,
      freshBeaconCount: freshBeaconCount,
      lastBleAgeMs: lastBleAgeMs,
      manifestRevision: manifestRevision,
      algorithmVersion: algorithmVersion,
      stale: stale,
      diagnosticFlags: diagnosticFlags
    )
  }
  func toList() -> [Any?] {
    return [
      sequence,
      monotonicTimestampMs,
      status,
      mode,
      floorId,
      floorProbability,
      local,
      accuracyRadiusM,
      headingDeg,
      headingAccuracyDeg,
      speedMps,
      freshBeaconCount,
      lastBleAgeMs,
      manifestRevision,
      algorithmVersion,
      stale,
      diagnosticFlags,
    ]
  }
  static func == (lhs: NativePositionEstimate, rhs: NativePositionEstimate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && MessagesPigeonInternal.deepEquals(lhs.monotonicTimestampMs, rhs.monotonicTimestampMs) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.mode, rhs.mode) && MessagesPigeonInternal.deepEquals(lhs.floorId, rhs.floorId) && MessagesPigeonInternal.deepEquals(lhs.floorProbability, rhs.floorProbability) && MessagesPigeonInternal.deepEquals(lhs.local, rhs.local) && MessagesPigeonInternal.deepEquals(lhs.accuracyRadiusM, rhs.accuracyRadiusM) && MessagesPigeonInternal.deepEquals(lhs.headingDeg, rhs.headingDeg) && MessagesPigeonInternal.deepEquals(lhs.headingAccuracyDeg, rhs.headingAccuracyDeg) && MessagesPigeonInternal.deepEquals(lhs.speedMps, rhs.speedMps) && MessagesPigeonInternal.deepEquals(lhs.freshBeaconCount, rhs.freshBeaconCount) && MessagesPigeonInternal.deepEquals(lhs.lastBleAgeMs, rhs.lastBleAgeMs) && MessagesPigeonInternal.deepEquals(lhs.manifestRevision, rhs.manifestRevision) && MessagesPigeonInternal.deepEquals(lhs.algorithmVersion, rhs.algorithmVersion) && MessagesPigeonInternal.deepEquals(lhs.stale, rhs.stale) && MessagesPigeonInternal.deepEquals(lhs.diagnosticFlags, rhs.diagnosticFlags)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePositionEstimate")
    MessagesPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: monotonicTimestampMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: floorId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: floorProbability, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: local, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: accuracyRadiusM, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headingDeg, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headingAccuracyDeg, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: speedMps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: freshBeaconCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lastBleAgeMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: manifestRevision, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: algorithmVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: diagnosticFlags, hasher: &hasher)
  }

  public var description: String {
    return "NativePositionEstimate(sequence: \(String(describing: sequence)), monotonicTimestampMs: \(String(describing: monotonicTimestampMs)), status: \(String(describing: status)), mode: \(String(describing: mode)), floorId: \(String(describing: floorId)), floorProbability: \(String(describing: floorProbability)), local: \(String(describing: local)), accuracyRadiusM: \(String(describing: accuracyRadiusM)), headingDeg: \(String(describing: headingDeg)), headingAccuracyDeg: \(String(describing: headingAccuracyDeg)), speedMps: \(String(describing: speedMps)), freshBeaconCount: \(String(describing: freshBeaconCount)), lastBleAgeMs: \(String(describing: lastBleAgeMs)), manifestRevision: \(String(describing: manifestRevision)), algorithmVersion: \(String(describing: algorithmVersion)), stale: \(String(describing: stale)), diagnosticFlags: \(String(describing: diagnosticFlags)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePositioningUpdate: Hashable, CustomStringConvertible {
  var mapId: String
  var groupId: String
  var estimate: NativePositionEstimate
  var wgs84: NativeWgs84Position? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePositioningUpdate? {
    let mapId = pigeonVar_list[0] as! String
    let groupId = pigeonVar_list[1] as! String
    let estimate = pigeonVar_list[2] as! NativePositionEstimate
    let wgs84: NativeWgs84Position? = nilOrValue(pigeonVar_list[3])

    return NativePositioningUpdate(
      mapId: mapId,
      groupId: groupId,
      estimate: estimate,
      wgs84: wgs84
    )
  }
  func toList() -> [Any?] {
    return [
      mapId,
      groupId,
      estimate,
      wgs84,
    ]
  }
  static func == (lhs: NativePositioningUpdate, rhs: NativePositioningUpdate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.mapId, rhs.mapId) && MessagesPigeonInternal.deepEquals(lhs.groupId, rhs.groupId) && MessagesPigeonInternal.deepEquals(lhs.estimate, rhs.estimate) && MessagesPigeonInternal.deepEquals(lhs.wgs84, rhs.wgs84)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePositioningUpdate")
    MessagesPigeonInternal.deepHash(value: mapId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: groupId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: estimate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wgs84, hasher: &hasher)
  }

  public var description: String {
    return "NativePositioningUpdate(mapId: \(String(describing: mapId)), groupId: \(String(describing: groupId)), estimate: \(String(describing: estimate)), wgs84: \(String(describing: wgs84)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeErrorMessage: Hashable, CustomStringConvertible {
  var code: String
  var message: String
  var recoverable: Bool
  var userAction: String
  var debugDetail: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let recoverable = pigeonVar_list[2] as! Bool
    let userAction = pigeonVar_list[3] as! String
    let debugDetail: String? = nilOrValue(pigeonVar_list[4])

    return NativeErrorMessage(
      code: code,
      message: message,
      recoverable: recoverable,
      userAction: userAction,
      debugDetail: debugDetail
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      recoverable,
      userAction,
      debugDetail,
    ]
  }
  static func == (lhs: NativeErrorMessage, rhs: NativeErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.recoverable, rhs.recoverable) && MessagesPigeonInternal.deepEquals(lhs.userAction, rhs.userAction) && MessagesPigeonInternal.deepEquals(lhs.debugDetail, rhs.debugDetail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: recoverable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userAction, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: debugDetail, hasher: &hasher)
  }

  public var description: String {
    return "NativeErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)), recoverable: \(String(describing: recoverable)), userAction: \(String(describing: userAction)), debugDetail: \(String(describing: debugDetail)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapReadyEvent: Hashable, CustomStringConvertible {
  var mapId: String
  var groupId: String
  var configRevision: String? = nil
  var manifestRevision: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapReadyEvent? {
    let mapId = pigeonVar_list[0] as! String
    let groupId = pigeonVar_list[1] as! String
    let configRevision: String? = nilOrValue(pigeonVar_list[2])
    let manifestRevision: Int64? = nilOrValue(pigeonVar_list[3])

    return NativeMapReadyEvent(
      mapId: mapId,
      groupId: groupId,
      configRevision: configRevision,
      manifestRevision: manifestRevision
    )
  }
  func toList() -> [Any?] {
    return [
      mapId,
      groupId,
      configRevision,
      manifestRevision,
    ]
  }
  static func == (lhs: NativeMapReadyEvent, rhs: NativeMapReadyEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.mapId, rhs.mapId) && MessagesPigeonInternal.deepEquals(lhs.groupId, rhs.groupId) && MessagesPigeonInternal.deepEquals(lhs.configRevision, rhs.configRevision) && MessagesPigeonInternal.deepEquals(lhs.manifestRevision, rhs.manifestRevision)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMapReadyEvent")
    MessagesPigeonInternal.deepHash(value: mapId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: groupId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: configRevision, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: manifestRevision, hasher: &hasher)
  }

  public var description: String {
    return "NativeMapReadyEvent(mapId: \(String(describing: mapId)), groupId: \(String(describing: groupId)), configRevision: \(String(describing: configRevision)), manifestRevision: \(String(describing: manifestRevision)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeFloorChangedEvent: Hashable, CustomStringConvertible {
  var floorId: String? = nil
  var source: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeFloorChangedEvent? {
    let floorId: String? = nilOrValue(pigeonVar_list[0])
    let source: String? = nilOrValue(pigeonVar_list[1])

    return NativeFloorChangedEvent(
      floorId: floorId,
      source: source
    )
  }
  func toList() -> [Any?] {
    return [
      floorId,
      source,
    ]
  }
  static func == (lhs: NativeFloorChangedEvent, rhs: NativeFloorChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.floorId, rhs.floorId) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeFloorChangedEvent")
    MessagesPigeonInternal.deepHash(value: floorId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
  }

  public var description: String {
    return "NativeFloorChangedEvent(floorId: \(String(describing: floorId)), source: \(String(describing: source)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeSpotSelectedEvent: Hashable, CustomStringConvertible {
  var spotId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSpotSelectedEvent? {
    let spotId: String? = nilOrValue(pigeonVar_list[0])

    return NativeSpotSelectedEvent(
      spotId: spotId
    )
  }
  func toList() -> [Any?] {
    return [
      spotId
    ]
  }
  static func == (lhs: NativeSpotSelectedEvent, rhs: NativeSpotSelectedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.spotId, rhs.spotId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSpotSelectedEvent")
    MessagesPigeonInternal.deepHash(value: spotId, hasher: &hasher)
  }

  public var description: String {
    return "NativeSpotSelectedEvent(spotId: \(String(describing: spotId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRouteChangedEvent: Hashable, CustomStringConvertible {
  var destinationSpotId: String? = nil
  var active: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRouteChangedEvent? {
    let destinationSpotId: String? = nilOrValue(pigeonVar_list[0])
    let active = pigeonVar_list[1] as! Bool

    return NativeRouteChangedEvent(
      destinationSpotId: destinationSpotId,
      active: active
    )
  }
  func toList() -> [Any?] {
    return [
      destinationSpotId,
      active,
    ]
  }
  static func == (lhs: NativeRouteChangedEvent, rhs: NativeRouteChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.destinationSpotId, rhs.destinationSpotId) && MessagesPigeonInternal.deepEquals(lhs.active, rhs.active)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRouteChangedEvent")
    MessagesPigeonInternal.deepHash(value: destinationSpotId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: active, hasher: &hasher)
  }

  public var description: String {
    return "NativeRouteChangedEvent(destinationSpotId: \(String(describing: destinationSpotId)), active: \(String(describing: active)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol NativeEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePositioningEvent: NativeEvent {
  var clientId: Int64
  var type: String
  var update: NativePositioningUpdate? = nil
  var status: String? = nil
  var capabilities: NativeCapabilityReport? = nil
  var motionHeading: NativeMotionHeadingReading? = nil
  var beaconSignals: [NativeBeaconSignalReading]? = nil
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePositioningEvent? {
    let clientId = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! String
    let update: NativePositioningUpdate? = nilOrValue(pigeonVar_list[2])
    let status: String? = nilOrValue(pigeonVar_list[3])
    let capabilities: NativeCapabilityReport? = nilOrValue(pigeonVar_list[4])
    let motionHeading: NativeMotionHeadingReading? = nilOrValue(pigeonVar_list[5])
    let beaconSignals: [NativeBeaconSignalReading]? = nilOrValue(pigeonVar_list[6])
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[7])

    return NativePositioningEvent(
      clientId: clientId,
      type: type,
      update: update,
      status: status,
      capabilities: capabilities,
      motionHeading: motionHeading,
      beaconSignals: beaconSignals,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      type,
      update,
      status,
      capabilities,
      motionHeading,
      beaconSignals,
      error,
    ]
  }
  static func == (lhs: NativePositioningEvent, rhs: NativePositioningEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.update, rhs.update) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities) && MessagesPigeonInternal.deepEquals(lhs.motionHeading, rhs.motionHeading) && MessagesPigeonInternal.deepEquals(lhs.beaconSignals, rhs.beaconSignals) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePositioningEvent")
    MessagesPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: update, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: motionHeading, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: beaconSignals, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativePositioningEvent(clientId: \(String(describing: clientId)), type: \(String(describing: type)), update: \(String(describing: update)), status: \(String(describing: status)), capabilities: \(String(describing: capabilities)), motionHeading: \(String(describing: motionHeading)), beaconSignals: \(String(describing: beaconSignals)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapViewEvent: NativeEvent {
  var viewId: Int64
  var type: String
  var ready: NativeMapReadyEvent? = nil
  var loadState: String? = nil
  var positioningStatus: String? = nil
  var position: NativePositioningUpdate? = nil
  var capabilities: NativeCapabilityReport? = nil
  var motionHeading: NativeMotionHeadingReading? = nil
  var beaconSignals: [NativeBeaconSignalReading]? = nil
  var floorChanged: NativeFloorChangedEvent? = nil
  var spotSelected: NativeSpotSelectedEvent? = nil
  var routeChanged: NativeRouteChangedEvent? = nil
  var externalUrl: String? = nil
  var error: NativeErrorMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapViewEvent? {
    let viewId = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! String
    let ready: NativeMapReadyEvent? = nilOrValue(pigeonVar_list[2])
    let loadState: String? = nilOrValue(pigeonVar_list[3])
    let positioningStatus: String? = nilOrValue(pigeonVar_list[4])
    let position: NativePositioningUpdate? = nilOrValue(pigeonVar_list[5])
    let capabilities: NativeCapabilityReport? = nilOrValue(pigeonVar_list[6])
    let motionHeading: NativeMotionHeadingReading? = nilOrValue(pigeonVar_list[7])
    let beaconSignals: [NativeBeaconSignalReading]? = nilOrValue(pigeonVar_list[8])
    let floorChanged: NativeFloorChangedEvent? = nilOrValue(pigeonVar_list[9])
    let spotSelected: NativeSpotSelectedEvent? = nilOrValue(pigeonVar_list[10])
    let routeChanged: NativeRouteChangedEvent? = nilOrValue(pigeonVar_list[11])
    let externalUrl: String? = nilOrValue(pigeonVar_list[12])
    let error: NativeErrorMessage? = nilOrValue(pigeonVar_list[13])

    return NativeMapViewEvent(
      viewId: viewId,
      type: type,
      ready: ready,
      loadState: loadState,
      positioningStatus: positioningStatus,
      position: position,
      capabilities: capabilities,
      motionHeading: motionHeading,
      beaconSignals: beaconSignals,
      floorChanged: floorChanged,
      spotSelected: spotSelected,
      routeChanged: routeChanged,
      externalUrl: externalUrl,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      viewId,
      type,
      ready,
      loadState,
      positioningStatus,
      position,
      capabilities,
      motionHeading,
      beaconSignals,
      floorChanged,
      spotSelected,
      routeChanged,
      externalUrl,
      error,
    ]
  }
  static func == (lhs: NativeMapViewEvent, rhs: NativeMapViewEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.viewId, rhs.viewId) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.ready, rhs.ready) && MessagesPigeonInternal.deepEquals(lhs.loadState, rhs.loadState) && MessagesPigeonInternal.deepEquals(lhs.positioningStatus, rhs.positioningStatus) && MessagesPigeonInternal.deepEquals(lhs.position, rhs.position) && MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities) && MessagesPigeonInternal.deepEquals(lhs.motionHeading, rhs.motionHeading) && MessagesPigeonInternal.deepEquals(lhs.beaconSignals, rhs.beaconSignals) && MessagesPigeonInternal.deepEquals(lhs.floorChanged, rhs.floorChanged) && MessagesPigeonInternal.deepEquals(lhs.spotSelected, rhs.spotSelected) && MessagesPigeonInternal.deepEquals(lhs.routeChanged, rhs.routeChanged) && MessagesPigeonInternal.deepEquals(lhs.externalUrl, rhs.externalUrl) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMapViewEvent")
    MessagesPigeonInternal.deepHash(value: viewId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ready, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: loadState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: positioningStatus, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: position, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: motionHeading, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: beaconSignals, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: floorChanged, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: spotSelected, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: routeChanged, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: externalUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeMapViewEvent(viewId: \(String(describing: viewId)), type: \(String(describing: type)), ready: \(String(describing: ready)), loadState: \(String(describing: loadState)), positioningStatus: \(String(describing: positioningStatus)), position: \(String(describing: position)), capabilities: \(String(describing: capabilities)), motionHeading: \(String(describing: motionHeading)), beaconSignals: \(String(describing: beaconSignals)), floorChanged: \(String(describing: floorChanged)), spotSelected: \(String(describing: spotSelected)), routeChanged: \(String(describing: routeChanged)), externalUrl: \(String(describing: externalUrl)), error: \(String(describing: error)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativePositioningConfiguration.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeOperationResult.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeClientCreateResult.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeCapabilityResult.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeMapCenterReticleCandidateResult.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeMapCenterReticleCandidate.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeCapabilityReport.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeBleCapabilities.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeAuthorizationCapabilities.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeSensorCapabilities.fromList(self.readValue() as! [Any?])
    case 139:
      return NativeLocalPosition.fromList(self.readValue() as! [Any?])
    case 140:
      return NativeWgs84Position.fromList(self.readValue() as! [Any?])
    case 141:
      return NativeMotionHeadingReading.fromList(self.readValue() as! [Any?])
    case 142:
      return NativeBeaconSignalReading.fromList(self.readValue() as! [Any?])
    case 143:
      return NativePositionEstimate.fromList(self.readValue() as! [Any?])
    case 144:
      return NativePositioningUpdate.fromList(self.readValue() as! [Any?])
    case 145:
      return NativeErrorMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return NativeMapReadyEvent.fromList(self.readValue() as! [Any?])
    case 147:
      return NativeFloorChangedEvent.fromList(self.readValue() as! [Any?])
    case 148:
      return NativeSpotSelectedEvent.fromList(self.readValue() as! [Any?])
    case 149:
      return NativeRouteChangedEvent.fromList(self.readValue() as! [Any?])
    case 150:
      return NativePositioningEvent.fromList(self.readValue() as! [Any?])
    case 151:
      return NativeMapViewEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativePositioningConfiguration {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeOperationResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeClientCreateResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCapabilityResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapCenterReticleCandidateResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapCenterReticleCandidate {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCapabilityReport {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeBleCapabilities {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAuthorizationCapabilities {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSensorCapabilities {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLocalPosition {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? NativeWgs84Position {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMotionHeadingReading {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? NativeBeaconSignalReading {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? NativePositionEstimate {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? NativePositioningUpdate {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? NativeErrorMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapReadyEvent {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? NativeFloorChangedEvent {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSpotSelectedEvent {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRouteChangedEvent {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? NativePositioningEvent {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapViewEvent {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MetamapsHostApi {
  func createClient(configuration: NativePositioningConfiguration, completion: @escaping (Result<NativeClientCreateResult, Error>) -> Void)
  func configureClient(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func clientCapabilities(clientId: Int64, completion: @escaping (Result<NativeCapabilityResult, Error>) -> Void)
  func requestClientAuthorization(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func startClient(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func stopClient(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func resetClient(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func resetClientPedestrianRoute(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func disposeClient(clientId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func loadMapView(viewId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func reloadMapView(viewId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func requestMapViewAuthorization(viewId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func startMapViewPositioning(viewId: Int64, requestAuthorization: Bool, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func stopMapViewPositioning(viewId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func resetMapViewPedestrianRoute(viewId: Int64, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func selectMapViewFloor(viewId: Int64, floorId: String?, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func showMapViewSpot(viewId: Int64, spotId: String, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func setMapViewDestination(viewId: Int64, spotId: String?, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func setMapViewLanguage(viewId: Int64, language: String, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func setMapViewCenterReticleEnabled(viewId: Int64, enabled: Bool, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
  func requestMapViewCenterReticleCandidate(viewId: Int64, completion: @escaping (Result<NativeMapCenterReticleCandidateResult, Error>) -> Void)
  func openMapViewExternalLink(viewId: Int64, url: String, completion: @escaping (Result<NativeOperationResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MetamapsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MetamapsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MetamapsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.createClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! NativePositioningConfiguration
        api.createClient(configuration: configurationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createClientChannel.setMessageHandler(nil)
    }
    let configureClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.configureClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.configureClient(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureClientChannel.setMessageHandler(nil)
    }
    let clientCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.clientCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clientCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.clientCapabilities(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clientCapabilitiesChannel.setMessageHandler(nil)
    }
    let requestClientAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestClientAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestClientAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.requestClientAuthorization(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestClientAuthorizationChannel.setMessageHandler(nil)
    }
    let startClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.startClient(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startClientChannel.setMessageHandler(nil)
    }
    let stopClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.stopClient(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopClientChannel.setMessageHandler(nil)
    }
    let resetClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.resetClient(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetClientChannel.setMessageHandler(nil)
    }
    let resetClientPedestrianRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClientPedestrianRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetClientPedestrianRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.resetClientPedestrianRoute(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetClientPedestrianRouteChannel.setMessageHandler(nil)
    }
    let disposeClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.disposeClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.disposeClient(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeClientChannel.setMessageHandler(nil)
    }
    let loadMapViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.loadMapView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadMapViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.loadMapView(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadMapViewChannel.setMessageHandler(nil)
    }
    let reloadMapViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.reloadMapView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reloadMapViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.reloadMapView(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      reloadMapViewChannel.setMessageHandler(nil)
    }
    let requestMapViewAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMapViewAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.requestMapViewAuthorization(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMapViewAuthorizationChannel.setMessageHandler(nil)
    }
    let startMapViewPositioningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startMapViewPositioning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startMapViewPositioningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let requestAuthorizationArg = args[1] as! Bool
        api.startMapViewPositioning(viewId: viewIdArg, requestAuthorization: requestAuthorizationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startMapViewPositioningChannel.setMessageHandler(nil)
    }
    let stopMapViewPositioningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopMapViewPositioning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMapViewPositioningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.stopMapViewPositioning(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopMapViewPositioningChannel.setMessageHandler(nil)
    }
    let resetMapViewPedestrianRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetMapViewPedestrianRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetMapViewPedestrianRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.resetMapViewPedestrianRoute(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetMapViewPedestrianRouteChannel.setMessageHandler(nil)
    }
    let selectMapViewFloorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.selectMapViewFloor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectMapViewFloorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let floorIdArg: String? = nilOrValue(args[1])
        api.selectMapViewFloor(viewId: viewIdArg, floorId: floorIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      selectMapViewFloorChannel.setMessageHandler(nil)
    }
    let showMapViewSpotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.showMapViewSpot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showMapViewSpotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let spotIdArg = args[1] as! String
        api.showMapViewSpot(viewId: viewIdArg, spotId: spotIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showMapViewSpotChannel.setMessageHandler(nil)
    }
    let setMapViewDestinationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewDestination\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapViewDestinationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let spotIdArg: String? = nilOrValue(args[1])
        api.setMapViewDestination(viewId: viewIdArg, spotId: spotIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMapViewDestinationChannel.setMessageHandler(nil)
    }
    let setMapViewLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewLanguage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapViewLanguageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let languageArg = args[1] as! String
        api.setMapViewLanguage(viewId: viewIdArg, language: languageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMapViewLanguageChannel.setMessageHandler(nil)
    }
    let setMapViewCenterReticleEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewCenterReticleEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapViewCenterReticleEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        api.setMapViewCenterReticleEnabled(viewId: viewIdArg, enabled: enabledArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMapViewCenterReticleEnabledChannel.setMessageHandler(nil)
    }
    let requestMapViewCenterReticleCandidateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewCenterReticleCandidate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMapViewCenterReticleCandidateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        api.requestMapViewCenterReticleCandidate(viewId: viewIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMapViewCenterReticleCandidateChannel.setMessageHandler(nil)
    }
    let openMapViewExternalLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.openMapViewExternalLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openMapViewExternalLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let urlArg = args[1] as! String
        api.openMapViewExternalLink(viewId: viewIdArg, url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openMapViewExternalLinkChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MetamapsFlutterApiProtocol {
  func decideMapViewExternalLinkOpensDefault(viewId viewIdArg: Int64, url urlArg: String, completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
class MetamapsFlutterApi: MetamapsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func decideMapViewExternalLinkOpensDefault(viewId viewIdArg: Int64, url urlArg: String, completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.metamaps_flutter.MetamapsFlutterApi.decideMapViewExternalLinkOpensDefault\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([viewIdArg, urlArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class EventsStreamHandler: PigeonEventChannelWrapper<NativeEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.metamaps_flutter.MetamapsEventChannel.events"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
