// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class NativePositioningConfiguration {
  NativePositioningConfiguration({
    required this.baseUrl,
    required this.mapSlug,
    this.groupId,
    required this.maxOfflineAgeMs,
    required this.motionPolicy,
    required this.beaconDiagnosticsEnabled,
  });

  String baseUrl;

  String mapSlug;

  String? groupId;

  int maxOfflineAgeMs;

  String motionPolicy;

  bool beaconDiagnosticsEnabled;

  List<Object?> _toList() {
    return <Object?>[
      baseUrl,
      mapSlug,
      groupId,
      maxOfflineAgeMs,
      motionPolicy,
      beaconDiagnosticsEnabled,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativePositioningConfiguration decode(Object result) {
    result as List<Object?>;
    return NativePositioningConfiguration(
      baseUrl: result[0]! as String,
      mapSlug: result[1]! as String,
      groupId: result[2] as String?,
      maxOfflineAgeMs: result[3]! as int,
      motionPolicy: result[4]! as String,
      beaconDiagnosticsEnabled: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePositioningConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(baseUrl, other.baseUrl) &&
        _deepEquals(mapSlug, other.mapSlug) &&
        _deepEquals(groupId, other.groupId) &&
        _deepEquals(maxOfflineAgeMs, other.maxOfflineAgeMs) &&
        _deepEquals(motionPolicy, other.motionPolicy) &&
        _deepEquals(beaconDiagnosticsEnabled, other.beaconDiagnosticsEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePositioningConfiguration(baseUrl: $baseUrl, mapSlug: $mapSlug, groupId: $groupId, maxOfflineAgeMs: $maxOfflineAgeMs, motionPolicy: $motionPolicy, beaconDiagnosticsEnabled: $beaconDiagnosticsEnabled)';
  }
}

class NativeOperationResult {
  NativeOperationResult({this.error});

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static NativeOperationResult decode(Object result) {
    result as List<Object?>;
    return NativeOperationResult(error: result[0] as NativeErrorMessage?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeOperationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeOperationResult(error: $error)';
  }
}

class NativeClientCreateResult {
  NativeClientCreateResult({this.clientId, this.error});

  int? clientId;

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[clientId, error];
  }

  Object encode() {
    return _toList();
  }

  static NativeClientCreateResult decode(Object result) {
    result as List<Object?>;
    return NativeClientCreateResult(
      clientId: result[0] as int?,
      error: result[1] as NativeErrorMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeClientCreateResult ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientId, other.clientId) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeClientCreateResult(clientId: $clientId, error: $error)';
  }
}

class NativeCapabilityResult {
  NativeCapabilityResult({this.report, this.error});

  NativeCapabilityReport? report;

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[report, error];
  }

  Object encode() {
    return _toList();
  }

  static NativeCapabilityResult decode(Object result) {
    result as List<Object?>;
    return NativeCapabilityResult(
      report: result[0] as NativeCapabilityReport?,
      error: result[1] as NativeErrorMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCapabilityResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(report, other.report) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCapabilityResult(report: $report, error: $error)';
  }
}

class NativeMapCenterReticleCandidateResult {
  NativeMapCenterReticleCandidateResult({this.candidate, this.error});

  NativeMapCenterReticleCandidate? candidate;

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[candidate, error];
  }

  Object encode() {
    return _toList();
  }

  static NativeMapCenterReticleCandidateResult decode(Object result) {
    result as List<Object?>;
    return NativeMapCenterReticleCandidateResult(
      candidate: result[0] as NativeMapCenterReticleCandidate?,
      error: result[1] as NativeErrorMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMapCenterReticleCandidateResult ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(candidate, other.candidate) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMapCenterReticleCandidateResult(candidate: $candidate, error: $error)';
  }
}

class NativeMapCenterReticleCandidate {
  NativeMapCenterReticleCandidate({
    required this.floorId,
    required this.longitude,
    required this.latitude,
    this.local,
  });

  String floorId;

  double longitude;

  double latitude;

  NativeLocalPosition? local;

  List<Object?> _toList() {
    return <Object?>[floorId, longitude, latitude, local];
  }

  Object encode() {
    return _toList();
  }

  static NativeMapCenterReticleCandidate decode(Object result) {
    result as List<Object?>;
    return NativeMapCenterReticleCandidate(
      floorId: result[0]! as String,
      longitude: result[1]! as double,
      latitude: result[2]! as double,
      local: result[3] as NativeLocalPosition?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMapCenterReticleCandidate ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(floorId, other.floorId) &&
        _deepEquals(longitude, other.longitude) &&
        _deepEquals(latitude, other.latitude) &&
        _deepEquals(local, other.local);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMapCenterReticleCandidate(floorId: $floorId, longitude: $longitude, latitude: $latitude, local: $local)';
  }
}

class NativeCapabilityReport {
  NativeCapabilityReport({
    required this.platform,
    required this.osVersion,
    required this.sdkVersion,
    required this.ble,
    required this.authorization,
    required this.sensors,
    required this.selectedProfile,
  });

  String platform;

  String osVersion;

  String sdkVersion;

  NativeBleCapabilities ble;

  NativeAuthorizationCapabilities authorization;

  NativeSensorCapabilities sensors;

  String selectedProfile;

  List<Object?> _toList() {
    return <Object?>[
      platform,
      osVersion,
      sdkVersion,
      ble,
      authorization,
      sensors,
      selectedProfile,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeCapabilityReport decode(Object result) {
    result as List<Object?>;
    return NativeCapabilityReport(
      platform: result[0]! as String,
      osVersion: result[1]! as String,
      sdkVersion: result[2]! as String,
      ble: result[3]! as NativeBleCapabilities,
      authorization: result[4]! as NativeAuthorizationCapabilities,
      sensors: result[5]! as NativeSensorCapabilities,
      selectedProfile: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCapabilityReport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platform, other.platform) &&
        _deepEquals(osVersion, other.osVersion) &&
        _deepEquals(sdkVersion, other.sdkVersion) &&
        _deepEquals(ble, other.ble) &&
        _deepEquals(authorization, other.authorization) &&
        _deepEquals(sensors, other.sensors) &&
        _deepEquals(selectedProfile, other.selectedProfile);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCapabilityReport(platform: $platform, osVersion: $osVersion, sdkVersion: $sdkVersion, ble: $ble, authorization: $authorization, sensors: $sensors, selectedProfile: $selectedProfile)';
  }
}

class NativeBleCapabilities {
  NativeBleCapabilities({
    required this.supported,
    required this.enabled,
    required this.rangingAvailable,
    required this.foregroundScan,
    required this.backgroundScan,
    required this.directionFinding,
    required this.channelSounding,
  });

  bool supported;

  bool enabled;

  bool rangingAvailable;

  bool foregroundScan;

  String backgroundScan;

  String directionFinding;

  String channelSounding;

  List<Object?> _toList() {
    return <Object?>[
      supported,
      enabled,
      rangingAvailable,
      foregroundScan,
      backgroundScan,
      directionFinding,
      channelSounding,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeBleCapabilities decode(Object result) {
    result as List<Object?>;
    return NativeBleCapabilities(
      supported: result[0]! as bool,
      enabled: result[1]! as bool,
      rangingAvailable: result[2]! as bool,
      foregroundScan: result[3]! as bool,
      backgroundScan: result[4]! as String,
      directionFinding: result[5]! as String,
      channelSounding: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeBleCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(supported, other.supported) &&
        _deepEquals(enabled, other.enabled) &&
        _deepEquals(rangingAvailable, other.rangingAvailable) &&
        _deepEquals(foregroundScan, other.foregroundScan) &&
        _deepEquals(backgroundScan, other.backgroundScan) &&
        _deepEquals(directionFinding, other.directionFinding) &&
        _deepEquals(channelSounding, other.channelSounding);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeBleCapabilities(supported: $supported, enabled: $enabled, rangingAvailable: $rangingAvailable, foregroundScan: $foregroundScan, backgroundScan: $backgroundScan, directionFinding: $directionFinding, channelSounding: $channelSounding)';
  }
}

class NativeAuthorizationCapabilities {
  NativeAuthorizationCapabilities({
    required this.location,
    required this.preciseLocation,
    required this.bluetoothScan,
    required this.motion,
  });

  String location;

  bool preciseLocation;

  String bluetoothScan;

  String motion;

  List<Object?> _toList() {
    return <Object?>[location, preciseLocation, bluetoothScan, motion];
  }

  Object encode() {
    return _toList();
  }

  static NativeAuthorizationCapabilities decode(Object result) {
    result as List<Object?>;
    return NativeAuthorizationCapabilities(
      location: result[0]! as String,
      preciseLocation: result[1]! as bool,
      bluetoothScan: result[2]! as String,
      motion: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAuthorizationCapabilities ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(location, other.location) &&
        _deepEquals(preciseLocation, other.preciseLocation) &&
        _deepEquals(bluetoothScan, other.bluetoothScan) &&
        _deepEquals(motion, other.motion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAuthorizationCapabilities(location: $location, preciseLocation: $preciseLocation, bluetoothScan: $bluetoothScan, motion: $motion)';
  }
}

class NativeSensorCapabilities {
  NativeSensorCapabilities({
    required this.stepDetector,
    required this.rotationVector,
    required this.gyroscope,
    required this.magnetometer,
    required this.barometer,
  });

  bool stepDetector;

  bool rotationVector;

  bool gyroscope;

  bool magnetometer;

  bool barometer;

  List<Object?> _toList() {
    return <Object?>[
      stepDetector,
      rotationVector,
      gyroscope,
      magnetometer,
      barometer,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSensorCapabilities decode(Object result) {
    result as List<Object?>;
    return NativeSensorCapabilities(
      stepDetector: result[0]! as bool,
      rotationVector: result[1]! as bool,
      gyroscope: result[2]! as bool,
      magnetometer: result[3]! as bool,
      barometer: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSensorCapabilities ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(stepDetector, other.stepDetector) &&
        _deepEquals(rotationVector, other.rotationVector) &&
        _deepEquals(gyroscope, other.gyroscope) &&
        _deepEquals(magnetometer, other.magnetometer) &&
        _deepEquals(barometer, other.barometer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSensorCapabilities(stepDetector: $stepDetector, rotationVector: $rotationVector, gyroscope: $gyroscope, magnetometer: $magnetometer, barometer: $barometer)';
  }
}

class NativeLocalPosition {
  NativeLocalPosition({required this.x, required this.y, required this.z});

  double x;

  double y;

  double z;

  List<Object?> _toList() {
    return <Object?>[x, y, z];
  }

  Object encode() {
    return _toList();
  }

  static NativeLocalPosition decode(Object result) {
    result as List<Object?>;
    return NativeLocalPosition(
      x: result[0]! as double,
      y: result[1]! as double,
      z: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLocalPosition || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(z, other.z);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLocalPosition(x: $x, y: $y, z: $z)';
  }
}

class NativeWgs84Position {
  NativeWgs84Position({
    required this.longitude,
    required this.latitude,
    required this.elevationM,
  });

  double longitude;

  double latitude;

  double elevationM;

  List<Object?> _toList() {
    return <Object?>[longitude, latitude, elevationM];
  }

  Object encode() {
    return _toList();
  }

  static NativeWgs84Position decode(Object result) {
    result as List<Object?>;
    return NativeWgs84Position(
      longitude: result[0]! as double,
      latitude: result[1]! as double,
      elevationM: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeWgs84Position || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(longitude, other.longitude) &&
        _deepEquals(latitude, other.latitude) &&
        _deepEquals(elevationM, other.elevationM);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeWgs84Position(longitude: $longitude, latitude: $latitude, elevationM: $elevationM)';
  }
}

class NativeMotionHeadingReading {
  NativeMotionHeadingReading({
    this.localHeadingDeg,
    this.magneticFieldAccuracy,
  });

  double? localHeadingDeg;

  String? magneticFieldAccuracy;

  List<Object?> _toList() {
    return <Object?>[localHeadingDeg, magneticFieldAccuracy];
  }

  Object encode() {
    return _toList();
  }

  static NativeMotionHeadingReading decode(Object result) {
    result as List<Object?>;
    return NativeMotionHeadingReading(
      localHeadingDeg: result[0] as double?,
      magneticFieldAccuracy: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMotionHeadingReading ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(localHeadingDeg, other.localHeadingDeg) &&
        _deepEquals(magneticFieldAccuracy, other.magneticFieldAccuracy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMotionHeadingReading(localHeadingDeg: $localHeadingDeg, magneticFieldAccuracy: $magneticFieldAccuracy)';
  }
}

class NativeBeaconSignalReading {
  NativeBeaconSignalReading({
    required this.beaconId,
    required this.uuid,
    required this.major,
    required this.minor,
    required this.floorId,
    required this.rssiDbm,
    required this.smoothedRssiDbm,
    required this.radioDistanceM,
    required this.configuredPosition,
    required this.configuredWgs84,
    this.devicePosition,
    this.deviceWgs84,
    this.configuredDistanceM,
    this.distanceDeltaM,
    required this.monotonicTimestampMs,
  });

  String beaconId;

  String uuid;

  int major;

  int minor;

  String floorId;

  double rssiDbm;

  double smoothedRssiDbm;

  double radioDistanceM;

  NativeLocalPosition configuredPosition;

  NativeWgs84Position configuredWgs84;

  NativeLocalPosition? devicePosition;

  NativeWgs84Position? deviceWgs84;

  double? configuredDistanceM;

  double? distanceDeltaM;

  int monotonicTimestampMs;

  List<Object?> _toList() {
    return <Object?>[
      beaconId,
      uuid,
      major,
      minor,
      floorId,
      rssiDbm,
      smoothedRssiDbm,
      radioDistanceM,
      configuredPosition,
      configuredWgs84,
      devicePosition,
      deviceWgs84,
      configuredDistanceM,
      distanceDeltaM,
      monotonicTimestampMs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeBeaconSignalReading decode(Object result) {
    result as List<Object?>;
    return NativeBeaconSignalReading(
      beaconId: result[0]! as String,
      uuid: result[1]! as String,
      major: result[2]! as int,
      minor: result[3]! as int,
      floorId: result[4]! as String,
      rssiDbm: result[5]! as double,
      smoothedRssiDbm: result[6]! as double,
      radioDistanceM: result[7]! as double,
      configuredPosition: result[8]! as NativeLocalPosition,
      configuredWgs84: result[9]! as NativeWgs84Position,
      devicePosition: result[10] as NativeLocalPosition?,
      deviceWgs84: result[11] as NativeWgs84Position?,
      configuredDistanceM: result[12] as double?,
      distanceDeltaM: result[13] as double?,
      monotonicTimestampMs: result[14]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeBeaconSignalReading ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(beaconId, other.beaconId) &&
        _deepEquals(uuid, other.uuid) &&
        _deepEquals(major, other.major) &&
        _deepEquals(minor, other.minor) &&
        _deepEquals(floorId, other.floorId) &&
        _deepEquals(rssiDbm, other.rssiDbm) &&
        _deepEquals(smoothedRssiDbm, other.smoothedRssiDbm) &&
        _deepEquals(radioDistanceM, other.radioDistanceM) &&
        _deepEquals(configuredPosition, other.configuredPosition) &&
        _deepEquals(configuredWgs84, other.configuredWgs84) &&
        _deepEquals(devicePosition, other.devicePosition) &&
        _deepEquals(deviceWgs84, other.deviceWgs84) &&
        _deepEquals(configuredDistanceM, other.configuredDistanceM) &&
        _deepEquals(distanceDeltaM, other.distanceDeltaM) &&
        _deepEquals(monotonicTimestampMs, other.monotonicTimestampMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeBeaconSignalReading(beaconId: $beaconId, uuid: $uuid, major: $major, minor: $minor, floorId: $floorId, rssiDbm: $rssiDbm, smoothedRssiDbm: $smoothedRssiDbm, radioDistanceM: $radioDistanceM, configuredPosition: $configuredPosition, configuredWgs84: $configuredWgs84, devicePosition: $devicePosition, deviceWgs84: $deviceWgs84, configuredDistanceM: $configuredDistanceM, distanceDeltaM: $distanceDeltaM, monotonicTimestampMs: $monotonicTimestampMs)';
  }
}

class NativePositionEstimate {
  NativePositionEstimate({
    required this.sequence,
    required this.monotonicTimestampMs,
    required this.status,
    required this.mode,
    this.floorId,
    required this.floorProbability,
    this.local,
    required this.accuracyRadiusM,
    this.headingDeg,
    this.headingAccuracyDeg,
    required this.speedMps,
    required this.freshBeaconCount,
    this.lastBleAgeMs,
    required this.manifestRevision,
    required this.algorithmVersion,
    required this.stale,
    required this.diagnosticFlags,
  });

  int sequence;

  int monotonicTimestampMs;

  String status;

  String mode;

  String? floorId;

  double floorProbability;

  NativeLocalPosition? local;

  double accuracyRadiusM;

  double? headingDeg;

  double? headingAccuracyDeg;

  double speedMps;

  int freshBeaconCount;

  int? lastBleAgeMs;

  int manifestRevision;

  String algorithmVersion;

  bool stale;

  List<String> diagnosticFlags;

  List<Object?> _toList() {
    return <Object?>[
      sequence,
      monotonicTimestampMs,
      status,
      mode,
      floorId,
      floorProbability,
      local,
      accuracyRadiusM,
      headingDeg,
      headingAccuracyDeg,
      speedMps,
      freshBeaconCount,
      lastBleAgeMs,
      manifestRevision,
      algorithmVersion,
      stale,
      diagnosticFlags,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativePositionEstimate decode(Object result) {
    result as List<Object?>;
    return NativePositionEstimate(
      sequence: result[0]! as int,
      monotonicTimestampMs: result[1]! as int,
      status: result[2]! as String,
      mode: result[3]! as String,
      floorId: result[4] as String?,
      floorProbability: result[5]! as double,
      local: result[6] as NativeLocalPosition?,
      accuracyRadiusM: result[7]! as double,
      headingDeg: result[8] as double?,
      headingAccuracyDeg: result[9] as double?,
      speedMps: result[10]! as double,
      freshBeaconCount: result[11]! as int,
      lastBleAgeMs: result[12] as int?,
      manifestRevision: result[13]! as int,
      algorithmVersion: result[14]! as String,
      stale: result[15]! as bool,
      diagnosticFlags: (result[16]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePositionEstimate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sequence, other.sequence) &&
        _deepEquals(monotonicTimestampMs, other.monotonicTimestampMs) &&
        _deepEquals(status, other.status) &&
        _deepEquals(mode, other.mode) &&
        _deepEquals(floorId, other.floorId) &&
        _deepEquals(floorProbability, other.floorProbability) &&
        _deepEquals(local, other.local) &&
        _deepEquals(accuracyRadiusM, other.accuracyRadiusM) &&
        _deepEquals(headingDeg, other.headingDeg) &&
        _deepEquals(headingAccuracyDeg, other.headingAccuracyDeg) &&
        _deepEquals(speedMps, other.speedMps) &&
        _deepEquals(freshBeaconCount, other.freshBeaconCount) &&
        _deepEquals(lastBleAgeMs, other.lastBleAgeMs) &&
        _deepEquals(manifestRevision, other.manifestRevision) &&
        _deepEquals(algorithmVersion, other.algorithmVersion) &&
        _deepEquals(stale, other.stale) &&
        _deepEquals(diagnosticFlags, other.diagnosticFlags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePositionEstimate(sequence: $sequence, monotonicTimestampMs: $monotonicTimestampMs, status: $status, mode: $mode, floorId: $floorId, floorProbability: $floorProbability, local: $local, accuracyRadiusM: $accuracyRadiusM, headingDeg: $headingDeg, headingAccuracyDeg: $headingAccuracyDeg, speedMps: $speedMps, freshBeaconCount: $freshBeaconCount, lastBleAgeMs: $lastBleAgeMs, manifestRevision: $manifestRevision, algorithmVersion: $algorithmVersion, stale: $stale, diagnosticFlags: $diagnosticFlags)';
  }
}

class NativePositioningUpdate {
  NativePositioningUpdate({
    required this.mapId,
    required this.groupId,
    required this.estimate,
    this.wgs84,
  });

  String mapId;

  String groupId;

  NativePositionEstimate estimate;

  NativeWgs84Position? wgs84;

  List<Object?> _toList() {
    return <Object?>[mapId, groupId, estimate, wgs84];
  }

  Object encode() {
    return _toList();
  }

  static NativePositioningUpdate decode(Object result) {
    result as List<Object?>;
    return NativePositioningUpdate(
      mapId: result[0]! as String,
      groupId: result[1]! as String,
      estimate: result[2]! as NativePositionEstimate,
      wgs84: result[3] as NativeWgs84Position?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePositioningUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mapId, other.mapId) &&
        _deepEquals(groupId, other.groupId) &&
        _deepEquals(estimate, other.estimate) &&
        _deepEquals(wgs84, other.wgs84);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePositioningUpdate(mapId: $mapId, groupId: $groupId, estimate: $estimate, wgs84: $wgs84)';
  }
}

class NativeErrorMessage {
  NativeErrorMessage({
    required this.code,
    required this.message,
    required this.recoverable,
    required this.userAction,
    this.debugDetail,
  });

  String code;

  String message;

  bool recoverable;

  String userAction;

  String? debugDetail;

  List<Object?> _toList() {
    return <Object?>[code, message, recoverable, userAction, debugDetail];
  }

  Object encode() {
    return _toList();
  }

  static NativeErrorMessage decode(Object result) {
    result as List<Object?>;
    return NativeErrorMessage(
      code: result[0]! as String,
      message: result[1]! as String,
      recoverable: result[2]! as bool,
      userAction: result[3]! as String,
      debugDetail: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeErrorMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) &&
        _deepEquals(message, other.message) &&
        _deepEquals(recoverable, other.recoverable) &&
        _deepEquals(userAction, other.userAction) &&
        _deepEquals(debugDetail, other.debugDetail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeErrorMessage(code: $code, message: $message, recoverable: $recoverable, userAction: $userAction, debugDetail: $debugDetail)';
  }
}

class NativeMapReadyEvent {
  NativeMapReadyEvent({
    required this.mapId,
    required this.groupId,
    this.configRevision,
    this.manifestRevision,
  });

  String mapId;

  String groupId;

  String? configRevision;

  int? manifestRevision;

  List<Object?> _toList() {
    return <Object?>[mapId, groupId, configRevision, manifestRevision];
  }

  Object encode() {
    return _toList();
  }

  static NativeMapReadyEvent decode(Object result) {
    result as List<Object?>;
    return NativeMapReadyEvent(
      mapId: result[0]! as String,
      groupId: result[1]! as String,
      configRevision: result[2] as String?,
      manifestRevision: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMapReadyEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mapId, other.mapId) &&
        _deepEquals(groupId, other.groupId) &&
        _deepEquals(configRevision, other.configRevision) &&
        _deepEquals(manifestRevision, other.manifestRevision);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMapReadyEvent(mapId: $mapId, groupId: $groupId, configRevision: $configRevision, manifestRevision: $manifestRevision)';
  }
}

class NativeFloorChangedEvent {
  NativeFloorChangedEvent({this.floorId, this.source});

  String? floorId;

  String? source;

  List<Object?> _toList() {
    return <Object?>[floorId, source];
  }

  Object encode() {
    return _toList();
  }

  static NativeFloorChangedEvent decode(Object result) {
    result as List<Object?>;
    return NativeFloorChangedEvent(
      floorId: result[0] as String?,
      source: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeFloorChangedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(floorId, other.floorId) &&
        _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeFloorChangedEvent(floorId: $floorId, source: $source)';
  }
}

class NativeSpotSelectedEvent {
  NativeSpotSelectedEvent({this.spotId});

  String? spotId;

  List<Object?> _toList() {
    return <Object?>[spotId];
  }

  Object encode() {
    return _toList();
  }

  static NativeSpotSelectedEvent decode(Object result) {
    result as List<Object?>;
    return NativeSpotSelectedEvent(spotId: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSpotSelectedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(spotId, other.spotId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSpotSelectedEvent(spotId: $spotId)';
  }
}

class NativeRouteChangedEvent {
  NativeRouteChangedEvent({this.destinationSpotId, required this.active});

  String? destinationSpotId;

  bool active;

  List<Object?> _toList() {
    return <Object?>[destinationSpotId, active];
  }

  Object encode() {
    return _toList();
  }

  static NativeRouteChangedEvent decode(Object result) {
    result as List<Object?>;
    return NativeRouteChangedEvent(
      destinationSpotId: result[0] as String?,
      active: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRouteChangedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(destinationSpotId, other.destinationSpotId) &&
        _deepEquals(active, other.active);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRouteChangedEvent(destinationSpotId: $destinationSpotId, active: $active)';
  }
}

sealed class NativeEvent {}

class NativePositioningEvent extends NativeEvent {
  NativePositioningEvent({
    required this.clientId,
    required this.type,
    this.update,
    this.status,
    this.capabilities,
    this.motionHeading,
    this.beaconSignals,
    this.error,
  });

  int clientId;

  String type;

  NativePositioningUpdate? update;

  String? status;

  NativeCapabilityReport? capabilities;

  NativeMotionHeadingReading? motionHeading;

  List<NativeBeaconSignalReading>? beaconSignals;

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[
      clientId,
      type,
      update,
      status,
      capabilities,
      motionHeading,
      beaconSignals,
      error,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativePositioningEvent decode(Object result) {
    result as List<Object?>;
    return NativePositioningEvent(
      clientId: result[0]! as int,
      type: result[1]! as String,
      update: result[2] as NativePositioningUpdate?,
      status: result[3] as String?,
      capabilities: result[4] as NativeCapabilityReport?,
      motionHeading: result[5] as NativeMotionHeadingReading?,
      beaconSignals: (result[6] as List<Object?>?)
          ?.cast<NativeBeaconSignalReading>(),
      error: result[7] as NativeErrorMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePositioningEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientId, other.clientId) &&
        _deepEquals(type, other.type) &&
        _deepEquals(update, other.update) &&
        _deepEquals(status, other.status) &&
        _deepEquals(capabilities, other.capabilities) &&
        _deepEquals(motionHeading, other.motionHeading) &&
        _deepEquals(beaconSignals, other.beaconSignals) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePositioningEvent(clientId: $clientId, type: $type, update: $update, status: $status, capabilities: $capabilities, motionHeading: $motionHeading, beaconSignals: $beaconSignals, error: $error)';
  }
}

class NativeMapViewEvent extends NativeEvent {
  NativeMapViewEvent({
    required this.viewId,
    required this.type,
    this.ready,
    this.loadState,
    this.positioningStatus,
    this.position,
    this.capabilities,
    this.motionHeading,
    this.beaconSignals,
    this.floorChanged,
    this.spotSelected,
    this.routeChanged,
    this.externalUrl,
    this.error,
  });

  int viewId;

  String type;

  NativeMapReadyEvent? ready;

  String? loadState;

  String? positioningStatus;

  NativePositioningUpdate? position;

  NativeCapabilityReport? capabilities;

  NativeMotionHeadingReading? motionHeading;

  List<NativeBeaconSignalReading>? beaconSignals;

  NativeFloorChangedEvent? floorChanged;

  NativeSpotSelectedEvent? spotSelected;

  NativeRouteChangedEvent? routeChanged;

  String? externalUrl;

  NativeErrorMessage? error;

  List<Object?> _toList() {
    return <Object?>[
      viewId,
      type,
      ready,
      loadState,
      positioningStatus,
      position,
      capabilities,
      motionHeading,
      beaconSignals,
      floorChanged,
      spotSelected,
      routeChanged,
      externalUrl,
      error,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeMapViewEvent decode(Object result) {
    result as List<Object?>;
    return NativeMapViewEvent(
      viewId: result[0]! as int,
      type: result[1]! as String,
      ready: result[2] as NativeMapReadyEvent?,
      loadState: result[3] as String?,
      positioningStatus: result[4] as String?,
      position: result[5] as NativePositioningUpdate?,
      capabilities: result[6] as NativeCapabilityReport?,
      motionHeading: result[7] as NativeMotionHeadingReading?,
      beaconSignals: (result[8] as List<Object?>?)
          ?.cast<NativeBeaconSignalReading>(),
      floorChanged: result[9] as NativeFloorChangedEvent?,
      spotSelected: result[10] as NativeSpotSelectedEvent?,
      routeChanged: result[11] as NativeRouteChangedEvent?,
      externalUrl: result[12] as String?,
      error: result[13] as NativeErrorMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMapViewEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(viewId, other.viewId) &&
        _deepEquals(type, other.type) &&
        _deepEquals(ready, other.ready) &&
        _deepEquals(loadState, other.loadState) &&
        _deepEquals(positioningStatus, other.positioningStatus) &&
        _deepEquals(position, other.position) &&
        _deepEquals(capabilities, other.capabilities) &&
        _deepEquals(motionHeading, other.motionHeading) &&
        _deepEquals(beaconSignals, other.beaconSignals) &&
        _deepEquals(floorChanged, other.floorChanged) &&
        _deepEquals(spotSelected, other.spotSelected) &&
        _deepEquals(routeChanged, other.routeChanged) &&
        _deepEquals(externalUrl, other.externalUrl) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMapViewEvent(viewId: $viewId, type: $type, ready: $ready, loadState: $loadState, positioningStatus: $positioningStatus, position: $position, capabilities: $capabilities, motionHeading: $motionHeading, beaconSignals: $beaconSignals, floorChanged: $floorChanged, spotSelected: $spotSelected, routeChanged: $routeChanged, externalUrl: $externalUrl, error: $error)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativePositioningConfiguration) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeOperationResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeClientCreateResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeCapabilityResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is NativeMapCenterReticleCandidateResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is NativeMapCenterReticleCandidate) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is NativeCapabilityReport) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NativeBleCapabilities) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NativeAuthorizationCapabilities) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is NativeSensorCapabilities) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is NativeLocalPosition) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is NativeWgs84Position) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is NativeMotionHeadingReading) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is NativeBeaconSignalReading) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is NativePositionEstimate) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is NativePositioningUpdate) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is NativeErrorMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is NativeMapReadyEvent) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is NativeFloorChangedEvent) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is NativeSpotSelectedEvent) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is NativeRouteChangedEvent) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is NativePositioningEvent) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is NativeMapViewEvent) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativePositioningConfiguration.decode(readValue(buffer)!);
      case 130:
        return NativeOperationResult.decode(readValue(buffer)!);
      case 131:
        return NativeClientCreateResult.decode(readValue(buffer)!);
      case 132:
        return NativeCapabilityResult.decode(readValue(buffer)!);
      case 133:
        return NativeMapCenterReticleCandidateResult.decode(readValue(buffer)!);
      case 134:
        return NativeMapCenterReticleCandidate.decode(readValue(buffer)!);
      case 135:
        return NativeCapabilityReport.decode(readValue(buffer)!);
      case 136:
        return NativeBleCapabilities.decode(readValue(buffer)!);
      case 137:
        return NativeAuthorizationCapabilities.decode(readValue(buffer)!);
      case 138:
        return NativeSensorCapabilities.decode(readValue(buffer)!);
      case 139:
        return NativeLocalPosition.decode(readValue(buffer)!);
      case 140:
        return NativeWgs84Position.decode(readValue(buffer)!);
      case 141:
        return NativeMotionHeadingReading.decode(readValue(buffer)!);
      case 142:
        return NativeBeaconSignalReading.decode(readValue(buffer)!);
      case 143:
        return NativePositionEstimate.decode(readValue(buffer)!);
      case 144:
        return NativePositioningUpdate.decode(readValue(buffer)!);
      case 145:
        return NativeErrorMessage.decode(readValue(buffer)!);
      case 146:
        return NativeMapReadyEvent.decode(readValue(buffer)!);
      case 147:
        return NativeFloorChangedEvent.decode(readValue(buffer)!);
      case 148:
        return NativeSpotSelectedEvent.decode(readValue(buffer)!);
      case 149:
        return NativeRouteChangedEvent.decode(readValue(buffer)!);
      case 150:
        return NativePositioningEvent.decode(readValue(buffer)!);
      case 151:
        return NativeMapViewEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class MetamapsHostApi {
  /// Constructor for [MetamapsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MetamapsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeClientCreateResult> createClient(
    NativePositioningConfiguration configuration,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.createClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[configuration],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeClientCreateResult;
  }

  Future<NativeOperationResult> configureClient(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.configureClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeCapabilityResult> clientCapabilities(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.clientCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeCapabilityResult;
  }

  Future<NativeOperationResult> requestClientAuthorization(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestClientAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> startClient(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> stopClient(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> resetClient(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> resetClientPedestrianRoute(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetClientPedestrianRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> disposeClient(int clientId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.disposeClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> loadMapView(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.loadMapView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> reloadMapView(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.reloadMapView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> requestMapViewAuthorization(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> startMapViewPositioning(
    int viewId,
    bool requestAuthorization,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.startMapViewPositioning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, requestAuthorization],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> stopMapViewPositioning(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.stopMapViewPositioning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> resetMapViewPedestrianRoute(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.resetMapViewPedestrianRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> selectMapViewFloor(
    int viewId,
    String? floorId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.selectMapViewFloor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, floorId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> showMapViewSpot(
    int viewId,
    String spotId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.showMapViewSpot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, spotId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> setMapViewDestination(
    int viewId,
    String? spotId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewDestination$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, spotId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> setMapViewLanguage(
    int viewId,
    String language,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewLanguage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, language],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> setMapViewCenterReticleEnabled(
    int viewId,
    bool enabled,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.setMapViewCenterReticleEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeMapCenterReticleCandidateResult>
  requestMapViewCenterReticleCandidate(int viewId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.requestMapViewCenterReticleCandidate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeMapCenterReticleCandidateResult;
  }

  Future<NativeOperationResult> openMapViewExternalLink(
    int viewId,
    String url,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.metamaps_flutter.MetamapsHostApi.openMapViewExternalLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeOperationResult;
  }
}

abstract class MetamapsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<bool> decideMapViewExternalLinkOpensDefault(int viewId, String url);

  static void setUp(
    MetamapsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.metamaps_flutter.MetamapsFlutterApi.decideMapViewExternalLinkOpensDefault$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_viewId = args[0]! as int;
          final String arg_url = args[1]! as String;
          try {
            final bool output = await api.decideMapViewExternalLinkOpensDefault(
              arg_viewId,
              arg_url,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Returns a broadcast [Stream] of events from the `events` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<NativeEvent> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.metamaps_flutter.MetamapsEventChannel.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NativeEvent;
  });
}
