{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.metamaps.positioning",
    "module": "metamap-positioning-core",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-core-0.5.0.aar",
          "url": "metamap-positioning-core-0.5.0.aar",
          "size": 115997,
          "sha512": "1965b6ba3ec80155d66522554bd6bbf456291af22824dc501914d4989aed7697ca3fa3a3acc6d0cb7de9da16c5edfb68c112c64abeac73c288179f92053fd50b",
          "sha256": "f8df22cc9610c9803509faa38ff9fb225e143f1047ae971dc5d8a1782a518544",
          "sha1": "cc27dbb452c5b100e668bdc3537ecf4adc6c5342",
          "md5": "668c374a71ecfe7501067af054077cc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-core-0.5.0.aar",
          "url": "metamap-positioning-core-0.5.0.aar",
          "size": 115997,
          "sha512": "1965b6ba3ec80155d66522554bd6bbf456291af22824dc501914d4989aed7697ca3fa3a3acc6d0cb7de9da16c5edfb68c112c64abeac73c288179f92053fd50b",
          "sha256": "f8df22cc9610c9803509faa38ff9fb225e143f1047ae971dc5d8a1782a518544",
          "sha1": "cc27dbb452c5b100e668bdc3537ecf4adc6c5342",
          "md5": "668c374a71ecfe7501067af054077cc6"
        }
      ]
    }
  ]
}
